### ISSUE TITLE
Ability to delete chapter from dashboard

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/lms#1011]
I couldn't find the option to delete a chapter from the LMS UI.

**Comment by iamejaaz** [comment]
![image](https://github.com/user-attachments/assets/9638b43d-868b-44d5-97ea-ae3e62d5dec0)
If you are talking about this delete button, then it is available now.

**Comment by anhlevfx** [comment]
Hi @iamejaaz , I installed the latest version, but don't have the button you mention, I tried with admin account. What should I do to active the button?

**Comment by iamejaaz** [comment]
> Hi @iamejaaz , I installed the latest version, but don't have the button you mention, I tried with admin account. What should I do to active the button?

Hi @anhlevfx Edit the course from the course details page. I have attached the video.

https://github.com/user-attachments/assets/5838e7f6-15e3-4800-918c-3dedd0abbf0e

**Comment by anhlevfx** [comment]
Thank you @iamejaaz it works!

**Comment by anhlevfx** [comment]
Hi @iamejaaz, the delete button you mentioned above only delete a lesion of a chapter. How to delete a chapter? I have one option is edit title in popup modal after press edit chapter button.

**Comment by iamejaaz** [comment]
> Hi @iamejaaz, the delete button you mentioned above only delete a lesion of a chapter. How to delete a chapter? I have one option is edit title in popup modal after press edit chapter button.

@anhlevfx  I'm sorry, I was wrong. I think there is no option to delete chapters from the LMS UI. You can delete them by switching to desk view
⬇️  Remove the record from the chapter's child table.
![image](https://github.com/user-attachments/assets/c10051d5-453b-43c9-bf63-8749c6132ae1)

**Comment by pateljannat** [comment]
Chapters can be deleted from the portal now.
