### ISSUE TITLE
Feature Request - Add Student Registration Page with Email and Password Option

### ISSUE THREAD

**Issue by baonguyen2310** [frappe/lms#1037]
Description:

I am considering using Frappe LMS to create an educational center, but I noticed that the platform lacks a simple, accessible registration page for users. For an LMS, especially in a scenario where multiple students will be signing up, it’s essential to have a straightforward registration process that allows users to sign up with just an email and password.

Feature Request:

Add a dedicated registration page for students that supports easy sign-up with email and password.
Simplify the overall registration process to make it more user-friendly.
In an LMS environment, enabling students to self-register without complications is a critical feature, especially for institutions that need to onboard students quickly and efficiently. The current process seems more complex than necessary, which could be a barrier for potential users.

Is there any plan to implement this kind of feature?

Thank you!

**Comment by pateljannat** [comment]
@baonguyen2310 

There is already a sign up form through which students can register.

<img width="1440" alt="Screenshot 2024-10-02 at 11 39 45 AM" src="https://github.com/user-attachments/assets/5ee64131-983d-45cc-8eaa-ed5fcb4087ad">

Make sure sign up is enabled on your system

**Comment by baonguyen2310** [comment]
I have been searching for enable registration for the past 5 days. I still don't know how to enable registration, I don't know where the form is, and in the form why there is no password field like usual. Please help me, thanks.

**Comment by pateljannat** [comment]
@baonguyen2310 https://discuss.frappe.io/t/enable-signup-for/130383/2?u=pateljannat

check this article

**Comment by baonguyen2310** [comment]
Thank you so much!
