### ISSUE TITLE
Quiz is not getting submitted on frappe school

### ISSUE THREAD

**Issue by saranesh-m20z** [frappe/lms#1054]
<img width="1440" alt="Screenshot 2024-10-10 at 2 00 49 PM" src="https://github.com/user-attachments/assets/a3cff2ff-9146-4ecf-a4a7-4a510b47d8e5">

Link - https://frappe.school/lms/courses/frappe-developer-certification/learn/5-2

**Comment by pateljannat** [comment]
Fixed with #1056
