### ISSUE TITLE
you can 't add instructeur in place Courses , no popup show up 

### ISSUE THREAD

**Issue by yahyaahrika** [frappe/lms#1055]
**Describe the bug**
no place to add instructeur , use docker local maching

**To Reproduce**
Courses -> new 
http://localhost:8000/lms/courses/new/edit

**Screenshots**
![image](https://github.com/user-attachments/assets/17d4983b-367a-442a-a58d-f61c8deba316)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Comment by yahyaahrika** [comment]
i find the way 
![image](https://github.com/user-attachments/assets/b2acb5d7-6fcc-4bc5-b728-ae86e706aef7)
![image](https://github.com/user-attachments/assets/14db2d5f-c380-4765-93ca-29b1fd76a77c)

**Comment by pateljannat** [comment]
@yahyaahrika Yes you have to make sure to add instructors as members and then give them the right role. Then add them as instructors in the course.
