### ISSUE TITLE
500 Internal Server Error at lms.lms.api.get_branding

### ISSUE THREAD

**Issue by sunuilhamp** [frappe/lms#1078]
**Describe the bug**
I Tried to change app logo from Settings, it changed, then when I refresh the page, the logo comeback to default with error above

**Environment**
I installed in docker, then made them in same docker network

**To Reproduce**
1. Go to '/lms/courses'
2. Click on lms logo then chose Settings, after that go to branding and change the logo
3. logo changed
4. refresh
5. logo back to default

**Expected behavior**
that should be not like that, right?

**Screenshots**
![error](https://github.com/user-attachments/assets/46b1131c-8a54-4f94-b487-eb75bf2e5154)

**Comment by pateljannat** [comment]
@sunuilhamp after changing the logo, make sure to press the Update button at the end of the dialog

**Comment by sunuilhamp** [comment]
of course, I already press the update button

**Comment by jacobbordignon** [comment]
Confirming I am also seeing this issue on both the Frappe Cloud and local development (from Git) variations.
