### ISSUE TITLE
SCORM

### ISSUE THREAD

**Issue by aidemkin** [frappe/lms#1082]
**Is your feature request related to a problem? Please describe.**

At the moment, Frappe LMS does not support the SCORM standard (both for course creation and playback). This significantly limits its potential for use by medium and large companies.

Based on my experience working with large corporations, I can confidently say that SCORM support is a critical factor in attracting new clients from the large business segment. Many companies have already invested significant resources into developing educational content based on SCORM, and transitioning to new software products is only feasible if they can continue to use this content.

**Describe the solution you'd like**
I kindly request that you consider implementing support for SCORM course playback. If SCORM course creation functionality is also developed, Frappe LMS could become a fully-fledged and competitive educational platform for large organizations.

**Describe alternatives you've considered**

**Additional context**

**Comment by aidemkin** [comment]
Hi, @NagariaHussain @pateljannat

please answer. Thank you!

**Comment by pateljannat** [comment]
@aidemkin I am already working on it.

**Comment by pateljannat** [comment]
@aidemkin do you have a SCORM package that you can share

**Comment by pateljannat** [comment]
@aidemkin Thanks, this was very helpful. Do you have any SCORM package that returns interaction data too?

**Comment by pateljannat** [comment]
Closed with #1132
