### ISSUE TITLE
time field issue in edit batch form

### ISSUE THREAD

**Issue by iamejaaz** [frappe/lms#1103]
**Describe the bug**
Start and end time values are not showing in the batch edit form.

**To Reproduce**
1. Go to Edit batch and check Start and End time field

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/6436474e-94dc-4666-be80-7931edb58e8d

**Comment by pateljannat** [comment]
Fixed with https://github.com/frappe/lms/pull/1183
