### ISSUE TITLE
Learning Paths

### ISSUE THREAD

**Issue by pateljannat** [frappe/lms#1116]
The course list currently shows all the live courses in the system that students can enroll in. This is the primary starting point of the learning journey. This can be changed through Learning Paths.

There will be a setting through which this can be enabled. When learning paths are enabled, the default course list will be replaced to show the learning paths of a logged-in student.

Moderators can create learning paths by adding courses and assigning them to students. The courses will have a sequence indicating the order in which students should approach them.

As a student, I'll have to complete the first course of the path before moving to the second. If I try enrolling myself in the second course before completing the first, the system will restrict me from doing so.

On the portal, Moderators will be able to see all the learning paths, assign them to students and see the progress students have made for each.

**Comment by oomerwaseem** [comment]
@pateljannat Few points to consider here.

1. The current feature of learning courses is one-by-one use cases for all students.
2. Another use case is there would be multiple courses which needs to be learned in parallel also along with other courses as well. For example - Sem-1 --> English 1, Maths 1, Language 1 to be learned in parallel, Sem 2 --> English 2, Maths 2, Language 2 to be learned in parallel

Also, another use case in the Learning Path is setting the path within the course. For example the student must complete Lesson 1 to proceed to Lesson 2 and then complete Lesson 2 to proceed Lesson 3, then complete an Assignment and then proceed to Lesson 4. (This could be with timeline to complete else marked as late and allow to continue or restrict or without timeline only restriction and next lessons will show after completion only.

Any plans to handle these use
