### ISSUE TITLE
How to override templates in LMS (Vue)

### ISSUE THREAD

**Issue by grafzahl-io** [frappe/lms#1175]
Hi alltogether,

I did a lot of research (including the Frappe School) but could not find a matching topic.
We are using the LMS app and need to customize parts of the frontend.
As the LMS frontend is build in Vue, we need a way to override it to keep the core LMS app updatable.

Maybe I misunderstood something but in general I found answers that suggest creating a new own app and mirroring the file structure of for that file you want to override and add related commands in the hooks.py.

But as Vue will build separately: how do we do that?
Is there an official recommondation how to safely override things in a Vue frontend?

To have a specific example: I want to alter the Badges for tags in frappe_bench/apps/lms/frontend/src/components/CourseCard.vue

Thanks in advance!

**Comment by grafzahl-io** [comment]
Thank you for your fast reply!

Do you have a public example or documentation for your override technique?

Wouldn`t it be desireable make the existing apps fully customizable (even if they are intended to be low-code)?

In my opinion, that would open it to more use cases.

**Comment by grafzahl-io** [comment]
For everyone who is also searching for a solution to this:
https://www.youtube.com/watch?v=OKrGJa2NnIs
In this video, he explains an acceptable solution

**Comment by agritheory** [comment]
I disagree that copying an entire app into another one is "acceptable". This does not represent the values of the Frappe Framework.

**Comment by grafzahl-io** [comment]
Sure, but I did not found a better solution.
As I have no choice, but forking the whole LMS, it is acceptable in order to move on with our modifications we need to do.
