### ISSUE TITLE
Allow adding top-level web pages

### ISSUE THREAD

**Issue by anandology** [frappe/lms#172]
With the current setup, it is not possible to add a top-level page with more than 4 characters in the name. It is because the we are using `website_route_rules` in the hooks.

One alternative appoach is to use a custom page renderer for rendering user profiles. With that the system checks if a user  is present with the name in url  and only when that fails it falls back to web pages. 

However, this has a small issue. If a new user signups up with the name of an existing page, the user profile will take precedence over the web page. We need to make sure we don't allow usernames with existing web pages. 

It would also be good to have  an LMS setting to list all the reserved usernames, so that we can reserve some names to use in future.

**Comment by anandology** [comment]
cc: @pateljannat

**Comment by NagariaHussain** [comment]
This no longer applies, we now have Vue based portal, closing this issue.
