### ISSUE TITLE
Username is becoming empty

### ISSUE THREAD

**Issue by anandology** [frappe/lms#176]
**Describe the bug**

When tried to change the username from edit-profile page to an existing username, the username of the username is reset to empty instead of giving an error.

**To Reproduce**
1. Go to https://mon.school/edit-profile
2. Change the username to some existing username, say `anand`
3. Notice that the username has become empty

**Expected behavior**
An error in the form indicating that the username is not available.

**Comment by pateljannat** [comment]
Unable to replicate the error. There is already a validation in place that shows up.

![Screenshot 2021-08-12 at 2 57 09 PM](https://user-images.githubusercontent.com/31363128/129173787-35154fbb-b264-4955-8b0b-50e8225a0a47.png)

**Comment by pateljannat** [comment]
@anandology can you please verify this issue again
