### ISSUE TITLE
Make the widgets work at the app-level instead of module-level

### ISSUE THREAD

**Issue by anandology** [frappe/lms#193]
**Is your feature request related to a problem? Please describe.**
Currently the widgets are at the module-level and works for the modules in the community app. It is not possible to have widgets in other apps or it is not possible to overwrite widgets. 

Switch the widgets to app-level to address this issue.

**Comment by pateljannat** [comment]
@anandology Since we have web templates we won't need these right?

**Comment by anandology** [comment]
This is independent of web templates. Right now it is hardcoded in the
widgets code which modules are allowed. I think it should be fixed.
