### ISSUE TITLE
Unable to change banner image in profile

### ISSUE THREAD

**Issue by Pooja-Thyagi** [frappe/lms#226]
I have uploaded an image for the banner in the [profile page](https://www.echolearn.org/users/India%20Inclusion%20Summit) but it does not update when saved.

![photo_2021-10-07 21 41 18](https://user-images.githubusercontent.com/92105988/136423209-61e83017-018e-49b3-adc5-753eda5a7695.jpeg)

**Comment by pateljannat** [comment]
Right now the banner on the profile page is a static one. It can't be changed. We do plan to add an option for users to upload banners in the near future.
