### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by v-pai** [frappe/lms#234]
## General
- [x] Favicon needs to be fixed
- [ ] Sign up / Signup; Frappe School / FSchool; the language is inconsistent throughout the website
- [x] Move to `gray-50` as the background color to keep this consistent with the rest of the frappe websites

## Homepage
- [x] 'Get Started' redirects users to the `/login#signup`. The button reads 'Get Started' but we redirect them to the login page, this is false advertising. If we want to redirect users to the login page, we should have a secondary button in the hero section.
- [x] 'Get Started' button doesn't do anything when a user is logged in
- [x] Rename 'Get started' to 'All Courses' and redirect users to `/courses`
- [x] Have a secondary button to 'Sign Up'
- [x] Rename 'Live Courses' to 'Popular Courses'. We'll continue to launch courses and this section continues to grow. Show only three courses under 'Popular Courses'
- [x] 'Upcoming Courses' should have a maximum of three courses

## Sign up page
- [x] Clicking on 'Get Started' in the homepage redirects users to `/login#signup'. The route defined here is poor. 
- [ ] This is the sign up page but the primary button reads 'Signup', this is inconsistent.
- [ ] There's also a byline that says 'Login to Frappe School'. 

## Login page
- [ ] Login has social login options available but sign up doesn't. This behaviour is inconsistent
- [ ] The design for 'Don't have an account? Sign up' is inconsistent when compared to the sign up page
    - <img width="280" alt="login card design" src="https://user-images.githubusercontent.com/81136551/136847579-1dac9b04-b9e0-4429-8b43-63001e4c88f8.png"> <img width="242" alt="Login page" src="https://user-images.githubusercontent.com/81136551/136847710-b6991f6e-0f48-4851-9d1c-0ff7e0dd9da1.png">

## Course Cards
- [x] When there are no ratings, the star icon isn't right aligned to the edge of the card
- [x] Profile image and name doesn't seem to be vertically aligned
- [x] Star and user icon and their respective numbers aren't vertically aligned
- [x] Reduce the gap between button name and arrow icon
- [x] Reduce the shadow on the tags
- [ ] Reduce the gap between the profile image and name
- [x] Better image for course cards
- [ ] We don't use circles for profile images anywhere in Frappe, we can revert to using rounded rectangles if they look good
- [ ] Spacing between # chapters and course title can be reduced
- [ ] # Chapters feels weird when the cover image for a course has a white background
  - <img width="185" alt="Course card with white cover image" src="https://user-images.githubusercontent.com/81136551/136848151-8a0fe238-c5ab-4a5a-a880-18dd1b105475.png">

## Course Banner
- [x] Remove the left and right padding for breadcrumbs
- [ ] Design a better banner for courses. This could be in line with user profile banners
- [ ] Alignment between 'Start Learning' and right arrow icon seems off, the arrow needs to be slightly lower
- [x] We say 'Start Learning' here but 'Get Started' on the home page, need to be consistent wrt messaging

## Course sections
- [x] Remove the left and right padding for section titles in the course details page
- [ ] Sections titles are 'Course Outline', 'Course Description', 'Creator', 'Overview', 'Reviews', and 'Discussions'. Apart from the first two, the two other section titles have the word course in it, seems redundant
- [ ] Consistent padding across cards
- [ ] Check font consistency, font defaults to system fonts at a few places

# Course Outline
- [ ] Reduce left padding, the gap between the arrow and the edge of the card
- [ ] Reduce space between topic and lesson
  - <img width="240" alt="Topics" src="https://user-images.githubusercontent.com/81136551/136885613-3aed7338-f25e-4390-91c5-51b99a042fb3.png">
- [x] Lock icon and topic are misaligned
- [x] `.card-divider` has a 2px border as opposed to 1px. Both top and bottom border is getting applied instead of either one of the two.

## Course Creator
- [ ] We won't use a circular image as a profile picture anywhere within frappe, we should keep this consistent for the creator card in Frappe School as well
- [ ] Increase bottom padding or reduce top padding to make the card feel more consistent

## Description
- [ ] There's extra bottom padding for paragraphs
- [ ] Fix paragraph bottom spacing

## Overview
- [x] Icon and content alignment
- [ ] The overview card seems bigger, wrt padding, as compared to the description card when laid out side-by-side

## Review
- [ ] Inset the user profile and star rating
- [ ] Reduce size of user profile image
- [ ] Improve reviewer readability
- [ ] Use lighter colors for stars, it's taking too much attention
- [ ] Add the tooltip as a part of the designs

## Course page
- [ ] Move outline to the left, can it be sticky? This would allow us to center the lesson content and put more emphasis on it
- [ ] Improve spacing between chapter and byline
- [ ] Increase height of individual lessons, feels compressed
  - <img width="240" alt="CleanShot 2021-10-12 at 09 30 32@2x" src="https://user-images.githubusercontent.com/81136551/136889175-b1aa1ef1-d3e0-4651-a94e-1509aa75398c.png">
- [ ] Consistent padding across cards
- [ ] Reduce bottom padding in lesson content, there seems to be extra spacing
- [x] Should the 'Next' button be primary?
- [ ] Mark as complete be next to the chapter name? Since the complete indicator shows up next to the chapter name
- [ ] Completed indicator and chapter name are not aligned
   - <img width="210" alt="completed tag when chapter is complete" src="https://user-images.githubusercontent.com/81136551/136889634-f8390ff4-709a-4f15-b908-04f3961143c1.png">
- [ ] Tick feels too big
- [x] Tick and title aren't vertically aligned
  - <img width="106" alt="Tick mark when chapter is complete" src="https://user-images.githubusercontent.com/81136551/136889733-960dfcb4-5df4-4ce1-b531-f9af7d112dd2.png">
- [x] Extra space jutting out for individual lessons
  - <img width="72" alt="lesson hover is not aligned well" src="https://user-images.githubusercontent.com/81136551/136889806-77678636-392d-45e2-9b60-ddd6df95d008.png">
- [x] Better way to mark a lesson as completed
- [ ] Course outline during the course feels like a distraction

## Coures page - Description
- [x] Better empty state for discussions
- [x] Start a discussion title in the modal is misaligned
- [x] The `hr` fills the entire width of the modal, we don't do this anywhere else
  - <img width="173" alt="title and hr in the start a discussion modal" src="https://user-images.githubusercontent.com/81136551/136890446-dce1529d-eadf-473a-bcf7-50f53820ed5e.png">
- [x] Fix padding in the start a discussion modal
- [ ] Find an easier way for people to start a discussion, button + modal takes longer than necessary

## About Us
- [ ] Copy needs to be fixed
- [ ] We have one line answers for everything in the FAQ, we should expand and show everything up front. We don't need to use the FAQ component for this
- [ ] Have team details in about us. Seeing people builds trust

**Comment by pateljannat** [comment]
Closing the issue since after redesigning, a lot of the remaining points are not valid anymore.
