### ISSUE TITLE
Clickable tags

### ISSUE THREAD

**Issue by Pooja-Thyagi** [frappe/lms#236]
Hey, is it possible to make the tags on the courses clickable?
So that it redirects you to a page with all courses that fall under the same tag?

<img width="1385" alt="Screenshot 2021-10-12 at 9 41 46 PM" src="https://user-images.githubusercontent.com/92105988/136995099-119982ec-39df-4794-9f04-5bfcf08be113.png">

**Comment by pateljannat** [comment]
@Pooja-Thyagi we don't have such a think right now, but we do plan to add search bar on this page in the future which will search based on these tags too.
