### ISSUE TITLE
Paid courses

### ISSUE THREAD

**Issue by pateljannat** [frappe/lms#259]
**Workflow:**

1. There will be a checkbox on the LMS Course doctype called **Is Paid Course**. 
2. If this is checked and a user on the course home page clicks on Start Learning, the user will be redirected to the payment gateway page.
3. When the user completes the payment they will be redirected to the first lesson of the course.

**Changes to design:**
1. Course Card will reflect that this is a paid course and the price of the course.
2. Course home page will also reflect the price of the course.

cc: @asbasawaraj

**Comment by Matthewenderle** [comment]
@pateljannat is this going to be integrated with paypal?

**Comment by pateljannat** [comment]
@Matthewenderle yes PayPal will also be an option

**Comment by Matthewenderle** [comment]
@pateljannat when do you think that the paid feature would be complete?

**Comment by pateljannat** [comment]
@Matthewenderle we are planning to pick this up in the next quarter.

**Comment by Matthewenderle** [comment]
> @Matthewenderle can I know where exactly are you using this app? Are you willing to sponsor this feature?

I am interested. Please send me an email at mattenderle488 at gmail dot com.

**Comment by Matthewenderle** [comment]
@pateljannat I haven't received an email yet. Is there a way to contact you directly?

**Comment by pateljannat** [comment]
@Matthewenderle based on our priorities, this quarter we decided to work on a [feature that allows users to create and edit courses from UI](https://github.com/frappe/lms/pull/357). I will be completing it this quarter.

I'll pick the feature to have Paid Courses in the LMS next quarter, most likely in the month of October. I will reach out to you then.

**Comment by pateljannat** [comment]
@Matthewenderle can I know your exact use case for paid courses? What flow do you have in mind for this?

**Comment by Matthewenderle** [comment]
@pateljannat 
We're really looking at doing subscriptions to access new content. We want users to be able to pay for a semester, or one calendar year (jan-dec), and then they get all the content assigned to that semester. Also, they should always have access to it, but not the next semester unless they pay for it.

**Comment by pateljannat** [comment]
@Matthewenderle in your case, will the student pay for all the courses of a semester together or will they pay separately for each course?

**Comment by Matthewenderle** [comment]
@pateljannat They will pay for the semester that contains a group of courses. So any courses released in 2023 will be included, unless it's a standalone course that is used to bring students in.

**Comment by Matthewenderle** [comment]
> @Matthewenderle @pateljannat Do we have this feature in lms currently ?

not sure. I dropped using Frappe and moved onto Moodle as I kept hitting roadblocks.

**Comment by divatemangesh** [comment]
I keep on getting queries for these features from my Educator friends, and the only reason I can't recommend frappe LMS(either Self-hosted/ or hosted by frappe) to them as it lacks the ability to collect payments, I strongly believe that once this is implemented  frappe LMS can become the open source alternative to Udemy, course-era

**Comment by harshpwctech** [comment]
@pateljannat - My suggestion here is to that we use the e-commerce implementation in ERPNext to provide paid courses and once the payment is made, the user shall be enrolled for the course.

@nabinhait  - Please let me know your thoughts on this.

**Comment by pateljannat** [comment]
#589

**Comment by shubham-prabhat** [comment]
LMS Paid course is not working as per expected,

currently user can by pass the Payment link button  and able to direct access of LMS Paid courses
