### ISSUE TITLE
Sessions / Events

### ISSUE THREAD

**Issue by pateljannat** [frappe/lms#284]
**Issue:** 
Most cohorts would have an online session for each lesson within each subgroup. The app must provide a way to link these online sessions to the lessons. 

**Solution:** 

 - A DocType called Online Session with the following fields.

	  1. Batch / Subgroup
	  2. Lesson
	  3. Call Link
	  4. Start DateTime
	  5. End DateTime

 - This session information will be displayed to the users on the lesson page. They can add this to their google calendar as an event with the click of a button.

 - Users will receive email reminders days before or on the day of the session.

**Comment by anandology** [comment]
I suggest making this flexible and call it event. The session could be about a lesson, welcome session, or a guest interaction or even ask me anything. The event could be online or offline. 

I also I think the event should be cohort-wide and not per subgroup.
