### ISSUE TITLE
Can't display courses from website

### ISSUE THREAD

**Issue by katzecz** [frappe/lms#320]
Does it work with version 13? Because I tried to get it working on  v13, which has been done correctly, but when accessing courses from the website by /courses URL, I get only this. Am I missing something? 

Also tried on fresh v13 install only with erpnext app installed.

Latest versions of erpnext and frappe installed

<img width="1314" alt="Snímek obrazovky 2022-03-29 v 22 28 09" src="https://user-images.githubusercontent.com/78561363/160701613-723dd25f-0c39-44e6-9c9e-0f075202fc8d.png">
.

**Comment by singhranbir** [comment]
> Does it work with version 13? Because I tried to get it working on v13, which has been done correctly, but when accessing courses from the website by /courses URL, I get only this. Am I missing something?
> 
> Also tried on fresh v13 install only with erpnext app installed.
> 
> Latest versions of erpnext and frappe installed
> 
> <img alt="Snímek obrazovky 2022-03-29 v 22 28 09" width="1314" src="https://user-images.githubusercontent.com/78561363/160701613-723dd25f-0c39-44e6-9c9e-0f075202fc8d.png">
> 
> .

i am also facing a same issue.

**Comment by pateljannat** [comment]
@katzecz @singhranbir is the site deployed anywhere? I would like to have a look. I am unable to replicate the issue on my side.

**Comment by katzecz** [comment]
@pateljannat you can check my test environment on https://school.bmslkv.cz/courses

Folder structure is the same as  on github, www folder included. 

Tried with main and version-13 branch.

**Comment by pateljannat** [comment]
@katzecz can you please provide a login access to me

**Comment by katzecz** [comment]
@pateljannat No problem, but I won’t share it publicly. Can you give your email, please?

**Comment by katzecz** [comment]
@pateljannat Yes, both branches.
I can setup courses from the desk, but can’t access them from website. 
Also, when I use section with courses in page builder then can’t even access that page.

**Comment by pateljannat** [comment]
@katzecz my email address is jannat@frappe.io. You can share the details there.

**Comment by katzecz** [comment]
@pateljannat Thanks, will send login details in a few minutes.

This is content of www folder.

![lms](https://user-images.githubusercontent.com/78561363/161750541-09994399-1cf7-466f-a855-34e2c438cb22.png)

**Comment by pateljannat** [comment]
@katzecz @singhranbir

LMS app has a folder called courses that renders the course list. ERPNext also has a template file with the same name. In my case, I had installed the LMS app first and then the ERPNext app. So at the time of rendering the page for path /courses,  the app LMS was getting preference as it was installed first. In your case it was the other way round, so the file from ERPNext was getting rendered.

I reached out to the ERPNext team and turns out the courses file in ERPNext is just a stale file and is not needed. [This](https://github.com/frappe/erpnext/pull/30596) Pull Request removes the file from ERPNext. This will fix the issue you are facing.

**Comment by katzecz** [comment]
It´s now working as expected. Thank you so much!

**Comment by singhranbir** [comment]
> @katzecz @singhranbir
> 
> LMS app has a folder called courses that renders the course list. ERPNext also has a template file with the same name. In my case, I had installed the LMS app first and then the ERPNext app. So at the time of rendering the page for path /courses, the app LMS was getting preference as it was installed first. In your case it was the other way round, so the file from ERPNext was getting rendered.
> 
> I reached out to the ERPNext team and turns out the courses file in ERPNext is just a stale file and is not needed. [This](https://github.com/frappe/erpnext/pull/30596) Pull Request removes the file from ERPNext. This will fix the issue you are facing.

I only have a frappe installed but it's not rendering the page
