### ISSUE TITLE
Allow users to put rating without a review to capture more feedback

### ISSUE THREAD

**Issue by wisharya** [frappe/lms#326]
The review form has a review field (small text type) which is mandatory for the learners. I think It shouldn't be mandatory, only the rating field should be. 

![Screenshot](https://user-images.githubusercontent.com/25725389/164306140-b0979403-0deb-49d3-8f83-a0512e2b4509.png)

I tried making it non-mandatory, but the field is already unchecked from the doctype. How to do it? 

Thanks

![Screenshot (1)](https://user-images.githubusercontent.com/25725389/164306682-9673fd0e-f84d-4095-8e33-03e3e460439f.png)

@pateljannat

**Comment by pateljannat** [comment]
@wisharya I have kept this validation in place in order to keep the inputs from different users consistent. Will think about making it non-mandatory though.

**Comment by wisharya** [comment]
IMO, from a good UX perspective, we shouldn't force them to write reviews. This reduces the number of ratings we get for each course.

**Comment by pateljannat** [comment]
To create a chapter, open the doctype Course Chapter.

1. Link the course to which this chapter belongs.
2. Give your chapter a title.
3. Provide a brief description.
4. In the Lessons table, link all the lessons that belong to this chapter.

**Comment by rmehta** [comment]
In most platforms, rating is mandatory, not everyone has time for a review - it just adds more friction - even in Frappe support system, we don't mandate reviews. We are losing valuable feedback from those who don't feel obliged to write a review

**Comment by pateljannat** [comment]
Closed by https://github.com/frappe/lms/pull/331
