### ISSUE TITLE
Option to capture organization/college at the time of signup

### ISSUE THREAD

**Issue by wisharya** [frappe/lms#330]
We should have a field to capture the organization/college at the time of signup.

**Why?**
Currently, we have the option to add college and organization under the edit profile form. But out of 10,500 users, only 148 students have added these data. Having a college/organization of users set gives us insight into our target audience.

**Comment by pateljannat** [comment]
@wisharya you can customize this for mon school. Frappe Framework now has a hook to add a custom template for signup.
You can check out this PR for the same. https://github.com/frappe/frappe/pull/15355

Just create a custom field for the user doctype through fixtures. Create a custom signup form. Pass this to the signup hook mentioned in the PR.

Let me know if you have any queries.

**Comment by wisharya** [comment]
It shows the message `Custom Fields cannot be added to core DocTypes.`

![Screenshot (14)](https://user-images.githubusercontent.com/25725389/169474829-0ae12cda-890c-4cf4-91e3-f8b7d9c32934.png)

![Screenshot (13)](https://user-images.githubusercontent.com/25725389/169474837-c8e126c1-e27e-4c54-a43c-72074ef42475.png)

**Comment by pateljannat** [comment]
@wisharya, you will have to use a fixture for that. Btw I was checking the lms app and we already have a custom field for college name. Maybe you can use the same field.

In the signup form that you create the label can be the College / Organization name

**Comment by pateljannat** [comment]
@wisharya as this has been implemented on mon school, I am closing the issue.
