### ISSUE TITLE
Work Experience field is mandatory in the profile page

### ISSUE THREAD

**Issue by wisharya** [frappe/lms#338]
I'm trying to edit my `username` on the profile page (`/edit-profile`), but after saving it shows 'Work Experience' is mandatory. I wanted to understand why it is mandatory.

![Screenshot (18)](https://user-images.githubusercontent.com/25725389/170438413-e7e8e3d6-2529-4d7b-b750-ecc224e1643a.png)

**Comment by pateljannat** [comment]
@wisharya I don't recall why this field was mandatory. This was not the intended behavior. I have changed it. You can try editing your profile now.

**Comment by wisharya** [comment]
Thanks. Closing this thread.
