### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by techseria** [frappe/lms#340]
We are getting a compilation error, please check below error log

Compiling Python files...
*** Error compiling '/opt/erp/frappe-bench/apps/lms/lms/www/courses/certificate.py'...
  File "/opt/erp/frappe-bench/apps/lms/lms/www/courses/certificate.py", line 34
    }
    ^
SyntaxError: invalid syntax

Python version: Python 3.8.10

**Comment by pateljannat** [comment]
Hey @techseria,

I have just pushed a change in this file. Can you take a pull of the main branch and see if the issue is gone?

**Comment by techseria** [comment]
the issue is fixed. Thanks for the immediate response.
