### ISSUE TITLE
Make a public dashboard

### ISSUE THREAD

**Issue by rmehta** [frappe/lms#362]
Transparency will bring in more ownership from the community.

**Comment by rmehta** [comment]
Screenshot?

**Comment by pateljannat** [comment]
It was attached to the PR

<img width="1440" alt="Screenshot 2022-10-18 at 10 54 29 AM" src="https://user-images.githubusercontent.com/31363128/196342616-b1e36e45-d7a7-4454-869a-3bb7cbfe2576.png">

**Comment by rmehta** [comment]
can we make this public, like `/stats` so people can see overall?
