### ISSUE TITLE
Allow everyone to create courses

### ISSUE THREAD

**Issue by rmehta** [frappe/lms#363]
- Everyone should be able to create course
- Show my courses on my profile
- Allow me to create a course from home page / my profile page / via menu

**Comment by pateljannat** [comment]
Anyone can now create courses on Frappe School and Mon School.

<img width="1440" alt="Screenshot 2022-09-08 at 6 29 44 PM" src="https://user-images.githubusercontent.com/31363128/189128179-3fa03551-da7a-4429-b812-0592b2296395.png">

<img width="1440" alt="Screenshot 2022-09-08 at 6 29 34 PM" src="https://user-images.githubusercontent.com/31363128/189128188-b5f9545b-3388-491d-a08b-c8ec3da06ada.png">
