### ISSUE TITLE
Migration of Content Masters, LMS Activity, Assessment, Assessment Reports from Education app.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/lms#367]
**Is your feature request related to a problem? Please describe.**
As LMS is actively maintained as a standalone app, and hence, there are a few redundant doctypes, and a few reporting and inbuilt Learning Management systems in the education module itself, which belongs to LMS when it is already separated into a standalone app, there is no point to have redundant features which actually creates confusion (even while searching from awesome-bar).

For example:
- Masters (Course, Chapters/Topic)
- Content Masters (Article, Video, Quiz)
- LMS Activity (Course Enrollment, Course Activity, Quiz Activity)
- Assessment (This may be part of LMS)
- Assessment Reports (This may be part of LMS)

**Describe the solution you'd like**
Let the Education module remain a management module instead of the conflicting interest of LMS management, and commendable work already carried for LMS standalone app which is having better UX and is more intuitive than legacy LMS developed in core.

What I propose is a solution to work out, migrating LMS related features from Education (naming this as legacy LMS) to the LMS app, this will remove bloat as well as enhance the objective of Learning Management.

_Even if you disagree with me at some point, there is no point in having 2 Learning Management (One is into core i.e. Education domain and the other one is LMS standalone app). Any user which is using LMS from the standalone app, it is literally creating contradictory with education module, in one environment._

PS: Enable Learning Management System option seems confusing to me, this should be "Enable LMS Portal" rather than just "Enable LMS".

Whats your views: @pateljannat @rmehta on this?

**Comment by pateljannat** [comment]
@asharamseervi we absolutely agree with you. In fact, this is already a part of our plan. We plan to have the LMS app handle all Learning Management Features. We will remove the LMS from the Education Module and have it only for the back office management of Schools and Colleges. 

At the moment we are focusing on adding and enhancing this LMS app. Cleanup of the Education Module will be picked up later.
