### ISSUE TITLE
Course with disable_self_learning still shows Start Learning button and allows user to enrol.

### ISSUE THREAD

**Issue by harshitaneja** [frappe/lms#385]
**Describe the bug**
Course with disable_self_learning still shows Start Learning button and allows user to enrol.

**To Reproduce**
1. Go to course page and check Disable Self Learning in Course Settings.
2. Create a new user to test and find that Start Learning button is visible and lets the new user self-enrol for the course.

**Expected behavior**
Once the disable_self_learning flag is set, new users should not be able to self-enrol in the course and "Start Learning" button shouldn't be visible on the course page for new users.  

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
 - Version 106

**Additional context**
Running on Frappe Cloud

**Comment by pateljannat** [comment]
This is working fine on my side. What is the Frappe and LMS version of your site?
