### ISSUE TITLE
 Unable to create new LMS Batch

### ISSUE THREAD

**Issue by QHD-sp** [frappe/lms#386]
**Describe the bug**
![image](https://user-images.githubusercontent.com/114915243/193982146-1308e569-5e85-4fb3-b45d-aa18abe655d8.png)

**To Reproduce**
1. Go to LMS Batch
2. Click on 'Add LMS Batch'
3. Fill in all the information -> Click 'Save'

**Expected behavior**
Can create new LMS Batch

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by pateljannat** [comment]
Was fixed with [this commit](https://github.com/frappe/lms/commit/1e66742d02c988d62f5a51311df3f1bdf396f5af). Please update your site.

**Comment by QHD-sp** [comment]
Thanks, Jannat

**Comment by QHD-sp** [comment]
My system still has the same error as above. How can I do LMS Batch generation?
