### ISSUE TITLE
Demo about loading a document (Video and Assignment) for Course Lesson

### ISSUE THREAD

**Issue by QHD-sp** [frappe/lms#387]
**Describe.**
I do not load some of the document formats for Course Lesson, specifically:
- Document is Video not from Youtube
- The document is Assignment. I followed the instructions but still can't load.

https://user-images.githubusercontent.com/114915243/194038528-34e2663f-328e-403b-bcec-eba39e9903c8.mp4

![image](https://user-images.githubusercontent.com/114915243/194039098-38615530-90dd-410f-87f1-b6d4a7f822b4.png)

======================
I need a guide specifically for this.

**Comment by pateljannat** [comment]
https://docs.frappelms.com/course-creation/add-a-lesson.html

You can refer to this document to understand how to add assignments and videos. Let me know if you have any further questions.
