### ISSUE TITLE
Empty state for courses

### ISSUE THREAD

**Issue by rmehta** [frappe/lms#389]
<img width="1116" alt="Screenshot 2022-10-06 at 12 28 18 PM" src="https://user-images.githubusercontent.com/140076/194235363-f1671a8d-bf0c-454a-adb0-7004003b8a77.png">

**Comment by pateljannat** [comment]
Addressed with #402

![image](https://user-images.githubusercontent.com/31363128/198288836-88c7fd66-03ba-4815-be22-14d86ca29aea.png)
