### ISSUE TITLE
Navigation Flow

### ISSUE THREAD

**Issue by rmehta** [frappe/lms#391]
Courses:
- Courses
- Upcoming
- Enrolled
- Created
- Under Review
- Stats

Profile:
- Profile
- Certificates
- Created
- Settings

Notifications
- On the user icon (dropdown)

**Comment by pateljannat** [comment]
Addressed with #402 

### Course List

![image](https://user-images.githubusercontent.com/31363128/198289748-f83b25f0-f272-4cfb-a49d-40eb3d2015f0.png)

### Profile

![image](https://user-images.githubusercontent.com/31363128/198289819-832dc701-2c75-4dbd-9ef0-639782bd3f8a.png)
