### ISSUE TITLE
Gamification / energy points

### ISSUE THREAD

**Issue by rmehta** [frappe/lms#392]
Settings
 - Points 
    - lesson completion
    - quiz completion
    - course completion
 - Badges
    - Add badges
    - Threshold 
    - Display badge on user profile

**Comment by thida-bcn** [comment]
thanks
we need those features

**Comment by mkashif1973** [comment]
thanks, when will we get these features available ?

**Comment by pateljannat** [comment]
@mkashif1973 We do plan to have this feature ready but no timeline has been decided for it yet.

**Comment by pateljannat** [comment]
#795
