### ISSUE TITLE
Need to add 'Instructor' field to Chapter

### ISSUE THREAD

**Issue by QHD-sp** [frappe/lms#396]
Each course will have multiple chapters and each chapter will have a different instructor. 
Therefore, an instructor field is needed, and this instructor belongs to the group of instructors of that course.
And it needs to be displayed on the website

**Comment by pateljannat** [comment]
A course can have multiple instructors. This feature is already a part of the LMS.

<img width="1440" alt="Screenshot 2022-10-10 at 1 12 57 PM" src="https://user-images.githubusercontent.com/31363128/194819108-71494775-6824-4d89-a10f-580b75604402.png">

A course also has multiple lessons. Suppose a course has 4 lessons. 2 lessons are by Author 1 and the rest by Author 2.

We show all the instructors of a course on the lesson page as well. So if a lesson is from Author 2, users can find them on top of every lesson.

**Comment by QHD-sp** [comment]
Suppose a course has 4 lessons: 2 lessons by Author 1 and the other by Author 2.
Instead of showing all Authors of a course on each lesson, why don't you make it clear that lesson 1 belongs to Author 1 and lesson 2 belongs to Author 2
