### ISSUE TITLE
Can't access  Batch website, Cohort website, Member website, Schedule website.

### ISSUE THREAD

**Issue by QHD-sp** [frappe/lms#403]
Apart from Courses website and Community website, I don't know how to access sites like Batch, Cohort, Member, Schedule like what I refered from you guys.
So, can you guide me how to access or how to create the above websites (Batch, Cohort, Member, Schedule)? I really need your help.

**Comment by pateljannat** [comment]
We don't have a web view for batches yet. But we plan to have it soon. 

Web view for cohorts can be accessed through Cohort Staff only. You can set up Cohort staff from the desk.

I guess Member is the same as the community page?

We don't have schedules in LMS yet.

If you want you can contribute to any of these.

**Comment by QHD-sp** [comment]
@pateljannat  
I thank you very much for helping me.
Can you give me more specific instructions on Cohort? I still don't understand the problem.
After I created Cohort Staff. How can I view Cohort on the website? (What is the URL path to Cohort?)

**Comment by pateljannat** [comment]
So this can be accessed through the course page itself. When a cohort staff visits the course page they will be able to see a Manage the course CTA.

On clicking it they will see the rest of the details.

<img width="1440" alt="Screenshot 2022-10-13 at 1 34 04 PM" src="https://user-images.githubusercontent.com/31363128/195538862-13bad89b-a5c3-46e2-b4f0-ad98151071ec.png">

**Comment by pateljannat** [comment]
I am checking this issue. Can I know how you run cohorts in your organization?

**Comment by QHD-sp** [comment]
> I am checking this issue. Can I know how you run cohorts in your organization?
@pateljannat 
Actually, I don't quite understand what the purpose of Cohort is for.
Cohort related doctypes that I see in LMS:
**1. Cohort**
I need you to explain the effect of some of the following fields:
**- Slug:** Due to the language difference, I really don't understand what 'Slug' means here. Purpose when using it?
**- Duration:** As I understand it, this field is the period. If so, it really is a useless field. Why not set it to automatically sum the time according to the data in the Begin Date and End Date fields.
**- Table [Cohort Web Page]:** What is this table actually? And how to enter information into this table? I think there are many people who have the same questions as me. Hopefully, you can add a snippet of input instructions below this table.
**2. Cohort Subgroup** 
(a sub-branch of Cohort)
**3. Cohort Staff and Cohort Mentor**
Too many roles in 1 Cohort?
I see up to 3 roles:
**- Instructor:** In the Cohort doctype, there is a requirement to enter an Instructor. Is this Instructor also the Instructor in the Course? Or, are these two schools completely different?
**- Mentor:** I think this is the Subgroup's academic advisor. What is the role of this role (Manager of Subgroup?)
**- Staff: Admin /
 Manager/Employee:** What are these roles for? Is it necessary or not?
**4. Cohort Join Request**
Presumably this Doctype will get information from outside the course website.
At the website, students will choose a Cohort and Subgroup -> request to join. This data will be updated to the Cohort Join Request in the App. Then the Admin/Mentor (or maybe the Manager/Instructor???) will proceed to approve/deny those join requests.
But it is worth mentioning here, that I have not seen or found a link to make a request to join a Cohort off the Website. Does it have flaws, or has it been hidden, or did I understand it wrong??

**Comment by pateljannat** [comment]
@QHD-sp the whole cohort module was community contributed. I understand that the UX of this module is not good. I will be refactoring this module in the future.

**Comment by fkalpana** [comment]
> web view for batches

Do we have  web view for batches  now ?
I can see it on frappeacedemy site ( https://frappe.school/schedule ) , but cant see any where in LMS.
