### ISSUE TITLE
Can't find course review button on website

### ISSUE THREAD

**Issue by QHD-sp** [frappe/lms#408]
**Describe the bug**

https://user-images.githubusercontent.com/114915243/196599655-498e9e93-e88a-4c6c-be1e-1349e8e1d1f0.mp4

1. Go to website Courses
2. Choose any Course
3. Scroll down to Reviews

**Expected behavior**
Request to display the rating button so that the user can rate the course.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by pateljannat** [comment]
@QHD-sp are you the instructor of the course? If yes then you won't be able to see the button.

**Comment by QHD-sp** [comment]
@pateljannat No. I visited the website as a student. It doesn't show a button for me to rate the course.
