### ISSUE TITLE
Module 'lms.lms.utils' has no attribute 'get_chart_data'

### ISSUE THREAD

**Issue by QHD-sp** [frappe/lms#410]
**Describe the bug**
After updating LMS. My website has reported an error.

![image](https://user-images.githubusercontent.com/114915243/196903780-64693ac8-49c7-44ba-9e1c-2b724db79862.png)

**To Reproduce**
1. Go to Website

**Expected behavior**
No more error messages like this are displayed.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by pateljannat** [comment]
Can you run bench build on your server and try?

**Comment by QHD-sp** [comment]
I tried it and it still gives me the same error.

**Comment by pateljannat** [comment]
I am unable to replicate this in any of my instances. Is your site on the latest version of Frappe and LMS? Can you try updating?

**Comment by QHD-sp** [comment]
I have installed latest frappe and LMS version.  But I still get that error.  you can visit my website to see the error: https://erpn1.dxmb.vn/courses

**Comment by pateljannat** [comment]
I will need your server access to debug this issue.
