### ISSUE TITLE
403 errors for some static assets : /

### ISSUE THREAD

**Issue by RajatMathew** [frappe/lms#415]
Some static assets like course thumbnails in the homepage does not load sometime. 

Found this in the devtools. Seems like they were XSS filtered.
```
x-xss-protection: 1; mode=block
```
### Some more context
The site was hosted on Frappe cloud.
Checked on multiple browsers/devices. Issue was present across all of them.
Assets load when logged in with accounts having admin access, but not when logged in with normal accounts(or when not logged in)

![frappe-issue](https://user-images.githubusercontent.com/20884258/197994154-9eaf08eb-68a9-4761-a5f8-6c2b7af47e3f.png)

**Comment by pateljannat** [comment]
When you upload images, there appears a checkbox in the modal called Private which is checked by default. If an asset is kept private, it won't be visible to everyone. You will have to change this setting for all the assets that are not visible from the File doctype.

**Comment by RajatMathew** [comment]
Hey Patel, the files were not set private. Checked just now.

Also the error seems randomly occurring. Sometimes stuff loads, sometimes it doesn't, regardless of these conditions:
1. When logged in with an admin
