### ISSUE TITLE
Adding Classes

### ISSUE THREAD

**Issue by rmehta** [frappe/lms#426]
The goal is to help instructors manage a group of students by tracking their progress.

As an instructor I should be able to:

- [x] Create a new class
- [x] Add courses to the class
- [x] Add students to the class
- [x] View the student list
- [x] Get the progress (%) of each student in the course
- [x] Review quiz performance
- [x] Get activity report (login, lesson completion, etc)

**Comment by pateljannat** [comment]
### Class List
<img width="1439" alt="Screenshot 2022-11-21 at 12 12 38 PM" src="https://user-images.githubusercontent.com/31363128/203899393-454cfad4-7d83-44f5-bead-3b5320e8ac3e.png">

### Class Courses
<img width="1440" alt="Screenshot 2022-11-21 at 12 12 52 PM" src="https://user-images.githubusercontent.com/31363128/203899402-dcb26e7f-e98f-4a32-b38b-8a3cb585ed65.png">

### Class Students
<img width="1440" alt="Screenshot 2022-11-25 at 9 38 53 AM" src="https://user-images.githubusercontent.com/31363128/203899436-28931ab5-9c8b-4e36-af25-af91f57d829a.png">

### Student Progress
<img width="1098" alt="Screenshot 2022-11-25 at 9 39 34 AM" src="https://user-images.githubusercontent.com/31363128/203899482-a1d35ed6-12a9-4359-be45-651cd2d9787d.png">

### Assignment
<img width="1359" alt="Screenshot 2022-11-25 at 9 23 23 AM" src="https://user-images.githubusercontent.com/31363128/203899514-6ae729a1-13f7-48e2-91ee-e0dfe63a39a4.png">

### Evaluation
<img width="995" alt="Screenshot 2022-11-23 at 3 09 53 PM" src="https://user-images.githubusercontent.com/31363128/203899500-fa3a99fc-161f-4a82-a9dd-11c4e54f1f0a.png">
