### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by chenhaoenen** [frappe/lms#435]
hi, I run the project with docker-compose, but get error
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/49124360/204085552-d0eefe88-5de5-4895-bfaa-7fe7fd68972d.png">

**Comment by chenhaoenen** [comment]
with this, I'm run docker-compose up  but get 
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/49124360/204089493-8bbef2ba-49a3-43c1-9199-a74965a0aace.png">


Administrator / admin cant login

**Comment by chenhaoenen** [comment]
UI like this 

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/49124360/204089530-95967f10-5d30-4df5-b60d-feacc03b4812.png">

**Comment by pateljannat** [comment]
Seems like a build issue. Can you try the `bench build` command

**Comment by asharamseervi** [comment]
Naah, not a build issue. Even when you install very first time on fresh instance, this will trigger and installation of app will not complete. @pateljannat 
Duplicate (refer: without docker-compose) at https://github.com/frappe/lms/issues/438#issuecomment-1345186416

**Comment by pateljannat** [comment]
@@asharamseervi please check my comment https://github.com/frappe/lms/issues/438#issuecomment-1345863340
