### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by mrn3** [frappe/lms#438]
**Describe the bug**
When I try to install this app to my site, I get an error

```
ubuntu@ip-172-31-34-101:~/frappe-bench$ bench --site internalerp.referralclass.net install-app lms

Installing lms...
Updating DocTypes for lms           : [======                                  ] 16%An error occurred while installing lms:
states
```

**To Reproduce**
1. Follow instructions in README on installing

**Expected behavior**
The app should install on the site

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: current

**Additional context**
Let me know if you need any other info to help fix.

**Comment by pateljannat** [comment]
I am unable to replicate this on my side.

Whats the version of frappe framework on your site?

**Comment by mrn3** [comment]
Sorry for the delay - it is 13 - perhaps I need to upgrade to 14?

**Comment by asharamseervi** [comment]
I can confirm, I had faced this issue yesterday, with _version-13_!

And, this one have something to do with states mentioned over here: `lms\lms\doctype\lesson_assignment\lesson_assignment.json`

Removing these states got it installed 100%, but obviously, missing these states functionality over Lesson Assignment doctype.
Workaround:
```
 "states": [
  {
   "color": "Green",
   "title": "Pass"
  },
  {
   "color": "Orange",
   "title": "Not Graded"
  },
  {
   "color": "Red",
   "title": "Fail"
  }
 ],
```
to
`"states": []`

**Comment by pateljannat** [comment]
@asharamseervi the main branch of the LMS app is not compatible with version-13 of the framework. For version-13 of the framework, there is a version-13 branch of LMS. The main branch of the LMS is compatible with version-14 and develop branch of the framework.

**Comment by mrn3** [comment]
Okay thanks - I will plan to upgrade to 14.
