### ISSUE TITLE
Unable to access Course creation

### ISSUE THREAD

**Issue by Matthewenderle** [frappe/lms#439]
**Describe the bug**
Just did a fresh install to get latest features. I can access the newer UI to create a course on [frappe.cloud](https://embnerdtest.frappe.cloud/courses/new-course), but not on my self-hosted one. I've using the administrator account on both.

The users can create courses from the backend editor ie: [https://example.com/app/lms-course/view/list](url)

**To Reproduce**
1. Login as 'Administrator'
2. Navigate to /courses/new-course

**Expected behavior**
New course UI should appear.

**Screenshots**
_From LMS on Frappe.cloud._
![image](https://user-images.githubusercontent.com/1463854/204969314-1dd60ff7-dc3e-49e4-834e-e63d244cf8f5.png)
![image](https://user-images.githubusercontent.com/1463854/204969937-f287b904-7875-48f4-b9d8-134b313df086.png)
![image](https://user-images.githubusercontent.com/1463854/204970035-6c4227d1-76ef-458a-a955-55cf965dbf7e.png)
![image](https://user-images.githubusercontent.com/1463854/204970452-b0687fc2-84ad-4b77-aa71-d0ba69d02557.png)

_From my self-hosted instance:_
![image](https://user-images.githubusercontent.com/1463854/204969820-ade1fc72-6e4e-4615-8ca7-d08330d6c3b8.png)
![image](https://user-images.githubusercontent.com/1463854/204969876-6622518e-e7a2-42fa-b1cf-308f62a95bff.png)
![image](https://user-images.githubusercontent.com/1463854/204969976-17377bd7-079e-4770-b55e-6a88247c529b.png)
![image](https://user-images.githubusercontent.com/1463854/204970464-78322c89-dde2-4423-a964-cf0be97efe36.png)

I also noticed that my user page looks different from the frappe.cloud version.
Mine:
![image](https://user-images.githubusercontent.com/1463854/204970312-0c256b00-b727-4cbd-94fe-6119bc89acf2.png)
FrappeCloud:
![image](https://user-images.githubusercontent.com/1463854/204970348-74633f22-a52d-49a5-af42-a3e801c5be62.png)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox and Edge
 - Version: 107 for both

**Additional context**
```
~/frappe-bench$ bench version
frappe 14.17.1
lms 0.0.1
```

I can provide credentials to login if requested.

**Comment by pateljannat** [comment]
On your self-hosted version, visit the doctype LMS Settings. Check the value of the field **Course Creation Access Through Website To**

If it's set to **Anyone**, then any user will be allowed to create courses from the website.
If it's set to **Course Instructor Role**, then only users with Instructor Role will be able to create courses.

**Comment by Matthewenderle** [comment]
@pateljannat my business partner was looking through the logs and determined that when we install the latest version it's not creating an 'Instructor Role' role. It is only doing 'Instructor'.

It leads me to believe that somewhere it's checking for the instructor role but a typo is making it append 'role' when it shouldn't be there. I have no idea where that is though.

**Comment by pateljannat** [comment]
@Matthewenderle the app is supposed to create the **Instructor** role and not the **Instructor Role** role. So what you have on your site is correct. Can you please share a screenshot of the LMS Settings doctype? Also, is your site hosted somewhere where I can access it?

**Comment by Matthewenderle** [comment]
> @Matthewenderle the app is supposed to create the **Instructor** role and not the **Instructor Role** role. So what you have on your site is correct. Can you please share a screenshot of the LMS Settings doctype? Also, is your site hosted somewhere where I can access it?

So I was mistaken. He created an `Instructor` role in addition to the already existing `Course Instructor` role one.
I'm having some other issues with not being able to access the course from the frontend. I'm fairly certain it's a SSL/NGINX/CLOUDFLARE issue.

I'd be more than willing to let you poke around, just not sure how to get you the credentials as I can't message you on github.

![image](https://user-images.githubusercontent.com/1463854/206804210-28878bf4-0217-4f83-a978-7b40f8196c11.png)

**Comment by Matthewenderle** [comment]
Disregard the SSL comment. If you don't have a lesson set for the first chapter under a course, after the student enrolls it will error 404. Just had to link it and then it worked.

**Comment by pateljannat** [comment]
@Matthewenderle 

> If you don't have a lesson set for the first chapter under a course, after the student enrolls it will error 404. Just had to link it and then it worked.

This is a valid issue. It has been addressed with #443
