### ISSUE TITLE
Wasn't able to upload Image through classess!

### ISSUE THREAD

**Issue by asharamseervi** [frappe/lms#445]
**Describe the bug**
I was exploring LMS and found, I wasn't able to attach image through Front-end despite having Administrator role!

**To Reproduce**
1. Create a new course, click over attach image button.
2. It will open dialogue box for attaching image with uploading button.
3. Attaching isn't working as expected.
4. Refer console errors:
- Uncaught ReferenceError: Vue is not defined
- Uncaught TypeError: this.uploader is undefined

**Screenshots**
![attach-image-from-course](https://user-images.githubusercontent.com/5942572/206978535-f9b9d997-b1ac-40f2-9c9a-435e179b0fcd.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Firefox
 - Frappe Version: v14

**Comment by pateljannat** [comment]
@asharamseervi is there any error in the console? Can you attach a screenshot of the same?

**Comment by asharamseervi** [comment]
Yes, there are! I already shared reference of those console log error's titles; let'me share detailed log:

<details>
<summary>Uncaught ReferenceError: Vue is not defined</summary>

```js
    Uncaught ReferenceError: Vue is not defined
    FileUploader index.js:31
    show_upload_modal new-course:1695
    <anonymous> new-course:1417
    jQuery 2
index.js:31:2
```

</details>

<details>
<summary>Uncaught TypeError: this.uploader is undefined</summary>

```js
    Uncaught TypeError: this.uploader is undefined
    on_page_show index.js:116
    make dialog.js:111
    jQuery 7
    transitionComplete2 modal.js:294
    fn jQuery
    handle util.js:35
    jQuery 8
    _showElement modal.js:301
    show modal.js:145
    fn jQuery
    handle util.js:35
    jQuery 8
    _showBackdrop modal.js:407
    show modal.js:145
    Modal2 modal.js:551
    jQuery 2
    _jQueryInterface modal.js:534
    show dialog.js:210
    make_dialog index.js:121
    FileUploader index.js:26
    show_upload_modal new-course:1695
    <anonymous> new-course:1417
    jQuery 2
index.js:116:4
```

</details>

<details>
<summary>Uncaught TypeError: this.uploader is undefined</summary>

```js
    Uncaught TypeError: this.uploader is undefined
    upload_files index.js:103
    primary_action index.js:110
    set_primary_action dialog.js:165
    jQuery 8
    set_primary_action dialog.js:158
    set_primary_action bootstrap-4-web.bundle.js:55
    make dialog.js:55
    make bootstrap-4-web.bundle.js:63
    Dialog dialog.js:17
    Dialog2 bootstrap-4-web.bundle.js:44
    make_dialog index.js:107
    FileUploader index.js:26
    show_upload_modal new-course:1695
    <anonymous> new-course:1417
    jQuery 2
index.js:103:2
```

</details>

**Comment by pateljannat** [comment]
I am unable to replicate this issue on my site. Can you please make sure that your site is up to date and try again. What branch of LMS is your site on?

**Comment by duc-nq** [comment]
Hi pateljannat, I has found the same issue in my system, can you fix it?
1. Upload image for change cover course photo
2. Can't not click Upload button to upload photo


> I am unable to replicate this issue on my site. Can you please make sure that your site is up to date and try again. What branch of LMS is your site on?

![Capture](https://user-images.githubusercontent.com/108884348/215154231-2aba5b84-07ad-4a5e-90ba-bcd31d0c15db.JPG)

**Comment by pateljannat** [comment]
@duc-nq What version of Frappe is your site on?

**Comment by duc-nq** [comment]
> 


> @duc-nq What version of Frappe is your site on?

My LMS site install on ERPnext version 14. Could you help me check this issue?

**Comment by pateljannat** [comment]
@duc-nq It works fine with develop branch of Frappe. I'll check why its not working on v14.

**Comment by duc-nq** [comment]
> @duc-nq It works fine with develop branch of Frappe. I'll check why its not working on v14.

Do you want check on my site?. I will send to you the account to login my site. You can check this more quickly.

**Comment by pateljannat** [comment]
@duc-nq sure if you can share the information that would help.

**Comment by jaosnxh** [comment]
![微信图片_20230309112531](https://user-images.githubusercontent.com/101778682/223909031-e19dc4ad-6634-4930-b710-73ddd5434c56.png)
![微信图片_20230309112440](https://user-images.githubusercontent.com/101778682/223909067-6fd60164-06ec-4fee-95f1-49066b906d43.png)
how to fix it?

**Comment by pateljannat** [comment]
works fine with the latest version
