### ISSUE TITLE
Lession sidebar fonts

### ISSUE THREAD

**Issue by rmehta** [frappe/lms#447]
Leaf nodes should have smaller font size

<img width="350" alt="Screenshot 2022-12-13 at 5 14 14 PM" src="https://user-images.githubusercontent.com/140076/207309288-4c9c2b87-96b1-414a-8d91-299218a255cc.png">

**Comment by pateljannat** [comment]
<img width="478" alt="Screenshot 2022-12-14 at 11 11 26 AM" src="https://user-images.githubusercontent.com/31363128/207515388-524b9481-a43b-4b39-ae65-ae427d53665b.png">
