### ISSUE TITLE
LMS Quiz Random Generator

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#471]
is this possible to generate Quiz randomly?
Example, 
I had 50 questions for specific lesson.
for each time when you do quiz, I want to show 10 questions.
Questions will change every time when user use quiz.

**Comment by pateljannat** [comment]
There is no such feature in the app. @thida-bcn

**Comment by thida-bcn** [comment]
hello,
will it be in system?

**Comment by zeel-codder** [comment]
Can I work on this issue? @pateljannat

**Comment by thida-bcn** [comment]
thanks
Thanks and Regards,
Thida
Business Development Director

Business Centric Network Company Limited
+959 977 160 671
+959 254 677 192
***@***.***
https://businesscentricnetwork.com/

**Comment by mkashif1973** [comment]
I made the following changes in the quiz.js file and successfully achieved the random question generation every time, details are as below:

**file location: lms/lms/templates/quiz/quiz.js**

**Insert the below codes between line 8 and line 9**
    // Shuffle questions once on page load
    let questions = $(".question");
    questions = Array.from(questions);
    const totalQuestions = questions.length;

    for (let i = questions.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [questions[i], questions[j]] = [questions[j], questions[i]];
    }

**changed line 51, 54, 56, 62 with the following (in sequence order):**
51	let current_index = self.current_index;

54	if (self.show_answers) {

56	} else if (!self.show_answers && next_index == total_questions) {

62	$(questions[next_index - 1])

I have checked this with 2 separate students login from different computers and from start to end both had different orders of questions secondly, I also reloaded the browser to start again also the sequence changed.

Please let me know your input.............

**Comment by pateljannat** [comment]
You can shuffle quiz questions on the latest version
