### ISSUE TITLE
Is there a way to Login and not see Courses Dashboard?

### ISSUE THREAD

**Issue by ablashek** [frappe/lms#472]
Hi!

I am using LMS alongside ERPNext for my inhouse training. Is there a way, when users log-in they go straight to desk instead of the course's dashboard? My idea is to use LMS to power my in-house employee training. Is this currently possible or a feature request?

**Comment by pmjd-code** [comment]
I have the same issue, the LMS will hopefully be a part of in-house training but not the focus of the installation, ERPNext Desk will be the focus.

**Comment by pateljannat** [comment]
@ablashek @pmjd-code I got your point. Will fix the issue.
