### ISSUE TITLE
After bench migrate markdown editor to Text Editor

### ISSUE THREAD

**Issue by mkashif1973** [frappe/lms#504]
after bench migrate our lms site updated markdown editor field with text editor but since then we are unable to attached videos by using 

Video | {{ Video("url_of_source") }}

Our OS and  application versions are as follows:

"Ubuntu 22.04.2 LTS"

frappe 14.32.1
lms 0.0.1

Please help how to upload videos from file list or else please guide how to revert text editor field to markdown editor.

Thanks

Kashif

**Comment by pateljannat** [comment]
@mkashif1973 I am looking into this issue.

**Comment by pateljannat** [comment]
@mkashif1973 we have upgraded the course builder. You should now be able to upload a local video using the new menu in the Lesson Details page. You should upgrade your site and try this now.

**Comment by mkashif1973** [comment]
Thanks, Jannat Patel, local video file is uploading but if we see it on preview it run the video but when user view it on lesson learning it wouldn't play the video.

frappe 14.36.0
lms 0.0.1


![lms-video](https://github.com/frappe/lms/assets/111403440/56a52fc5-0a6b-4200-a927-e7ce2b940b15)

When click on the play icon nothing happens and screen remains BLANK.

**Comment by mkashif1973** [comment]
see below it is showing and playing the video in preview but not in live class ?

![image](https://github.com/frappe/lms/assets/111403440/d120960f-9309-4132-9470-ba0a9293eded)

**Comment by mkashif1973** [comment]
Thanks issue resolve as I found that attached file name should be without spaces.

Thanks Patel Jannat
