### ISSUE TITLE
Certificate issued even no quiz attend by user

### ISSUE THREAD

**Issue by mkashif1973** [frappe/lms#531]
it has been noticed that lms issued a certificate to a user who complete all lessons without opening any quiz and system considered his course is 100% completed and issued the certificate as well through "Get Certificate" while system should not complete the status to 100% till all lessons with their quizzes not attend by the user.

also once user open the lesson even for 30 seconds system automatically considered it completed while in my openion at the time of lesson creation its minimum duration should need to be set enabling user to remain open the lesson till that time.

Kind Regards,

Kashif

**Comment by mkashif1973** [comment]
Is above considerable and in your list of correction or else please suggest ?

**Comment by pateljannat** [comment]
@mkashif1973 yes

**Comment by pateljannat** [comment]
@mkashif1973 for quiz you can now set a pass percentage and the quiz will only be marked complete if this percentage is met.
