### ISSUE TITLE
add LMS class with wrong dates

### ISSUE THREAD

**Issue by mkashif1973** [frappe/lms#538]
whenever we create a new class and when we select data from calendar it automatically change the date to 2020 year, below is the screen shot

![image](https://github.com/frappe/lms/assets/111403440/a4991c3c-8e30-4b44-88d9-9d1af9196a8b)

**Comment by mkashif1973** [comment]
ok, but how can i switch to develop branch, can you please guide me.

Please note that i have multi tenant enable in my machine and running erpnext v14 on different port and don't want to change them so please guide accordingly how can only change to LMS only

**Comment by pateljannat** [comment]
@mkashif1973  Is your erpnext and lms site on the same bench?

**Comment by pateljannat** [comment]
@mkashif1973  if they are on different benches then no issues.

Just switch the branch of the LMS site bench and then run the following commands

```
bench setup requirements
bench build
```

**Comment by mkashif1973** [comment]
But i have all apps in one bench

**Comment by mkashif1973** [comment]
Will it be ok to execute ?

**Comment by pateljannat** [comment]
@mkashif1973 if the apps are in same bench then can you create a new bench just for LMS site?

**Comment by mkashif1973** [comment]
Yes i can create new bench for lms site but how can you please guide?

Yes i am self hosted all of my sites.

**Comment by pateljannat** [comment]
@mkashif1973 follow the steps mentioned here. https://frappeframework.com/docs/v14/user/en/tutorial/install-and-setup-bench

Also, can I know why you are self-hosting and not using Frappe Cloud? It will be much less hassle for you and will also be cheaper.

**Comment by mkashif1973** [comment]
thanks, as far as self-hosting we have a lead who wants to setup self-hosted lms

**Comment by pateljannat** [comment]
@mkashif1973 did the new bench work for you? Also why does your client want to self host and not use FC?

**Comment by mkashif1973** [comment]
yes it works.

because of his data privacy and not interested on cloud services.

**Comment by pateljannat** [comment]
Okay, if it works can you close the issue?

**Comment by mkashif1973** [comment]
Ok I will, you earlier replied that there is an incompatibility between Frappe v14 and LMS, can you please guide the compatibilities of LMS with .......?

**Comment by pateljannat** [comment]
LMS is compatible with the develop branch of Frappe @mkashif1973
