### ISSUE TITLE
Can't add Preview Image on create Course in LMS frontend

### ISSUE THREAD

**Issue by kittiu** [frappe/lms#543]
**Describe the bug**
Can't add Preview Image on create Course in LMS frontend

**To Reproduce**
Just create a course, and you won't be able to add image,

![image](https://github.com/frappe/lms/assets/1973598/caa92e4b-ddfd-4480-9e66-d8bd9c760a7d)

I have to go back to desk to add it.

I am using this version,
https://github.com/frappe/lms/commit/af9aa3e37be4ea0641cced6160def8d60623cbef

**Comment by pateljannat** [comment]
@kittiu you must be on Frappe v14?

You will need to be on Frappe develop to use this. Is it feasible for you?

**Comment by kittiu** [comment]
Ok you mean the fix has been made but not deployed?

**Comment by pateljannat** [comment]
No I mean that you will have to be on Frappe's develop branch to use LMS
