### ISSUE TITLE
Quiz option "User Input"

### ISSUE THREAD

**Issue by mkashif1973** [frappe/lms#547]
There is a very good option available in quiz that is "User Input" option but there is a problem in this quiz answer as it exactly match the whole sentence while in these type of questions answer will be little change for example:

Question: How many colors is UK flag?

there are (03) colors in UK flag but there are many ways user can write the answer e.g. 

ANSWERS:
03 Colors
Three Colors
There are 3 colors in UK flag
There are three colors in UK flag
It has 03 colors
It has three colors
three colors, white, red, blue
etc.. etc... etc...

all above answers are correct and even more way user can write the correct answer, I hope this explanation will be good enough to explain you our point of view, please consider to address the same and provide the appropriate possible solution.

Kind Regards,

Kashif

**Comment by thida-bcn** [comment]
I'm agreed too.
For user input questions, system should not check automatically.

**Comment by mkashif1973** [comment]
Hi, 
Is Above suggestion is considerable ? And if so when we will expect this ?
Kind Regards,

**Comment by pateljannat** [comment]
In the new version the answer correction will be decided based on Fuzzy matching,
