### ISSUE TITLE
All users can start learning 

### ISSUE THREAD

**Issue by mkashif1973** [frappe/lms#550]
all type of user's including Moderator, Teacher, Administrator are able to start learning in the class or the courses, but I think these users type are only manage the application while only student type users are allowed to learn the courses/classes

Kind Regards,

Kashif

**Comment by pateljannat** [comment]
@mkashif1973 this is not necessary.

@mkashif1973  We have seen many community learning instances where a user can be a moderator of the platform and a student for one of the courses.

Hence the button is visible to all kinds of users.
