### ISSUE TITLE
Quiz Questions workflow enhancement to improve reusablity.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/lms#553]
**Is your feature request related to a problem? Please describe.**
In order to improve user experience and regarding the reusability of questions, the quiz questions should be decoupled as they are now. A better workflow structure should be adapted to use questions from the questions bank. 

**Describe the solution you'd like**
As of now, there are chances of redundancy in the questions, while what can be improved is by assigning an identity to each question like ID, Topic, Subject, Difficulty, etc; by this way, course creators can reduce so much hustle! 

**Describe alternatives you've considered**
This Is a beginning, just thinking out loud. But you can follow along.

**Additional context**

**Comment by pateljannat** [comment]
Question is a new doctype now. So questions can be reused from there.
