### ISSUE TITLE
file upload

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#563]
file upload is not working well

**Comment by ahmadRagheb** [comment]
we found this issue too while working on lms for the first time ,  
i will start to fix it and add a pr if i was succeess in doing so .

**Comment by thida-bcn** [comment]
thanks
Thanks and Regards,
Thida
Business Development Director

Business Centric Network Company Limited
+959 977 160 671
+959 254 677 192
***@***.***
https://businesscentricnetwork.com/

**Comment by thida-bcn** [comment]
> we found this issue too while working on lms for the first time , i will start to fix it and add a pr if i was succeess in doing so .

thank you

**Comment by ahmadRagheb** [comment]
i managed to fix it on my setup , it comes from frappe 
the issue it can't see the function  __ translation ( since this function should be exposed in the frontend by translate.js in frappe-web.bundle.js ) this cause error and stop the upload feature , to slove it delete all the __ in FileUploader.vue in frappe app .

**Comment by ahmadRagheb** [comment]
also function frappe.utils.icon( 
not working in FilePreview,vue 
you should stop some of them to get workign 

also in number_format.js 
line 177 , it cant see the variables , 	so i change it hardcoding  to 
rounding_method =		 "Banker's Rounding (legacy)";

**Comment by ahmadRagheb** [comment]
my team can upload data and work on lms , meanwhile i will try to fix these issues and send pr to frappe i which they accept

**Comment by pateljannat** [comment]
@thida-bcn are you on version-14 of Frappe?

**Comment by thida-bcn** [comment]
> @thida-bcn are you on version-14 of Frappe?

yes, i'm on v-14 latest version

**Comment by pateljannat** [comment]
I recommend that you switch to Frappe develop branch because that is compatible with the LMS App.
