### ISSUE TITLE
LMS Quiz Submission without Question

### ISSUE THREAD

**Issue by mkashif1973** [frappe/lms#565]
When we check user response on Quiz Submission, it shows the **question field Blank (no data)** while answer and correct fields OK.
 
below is the screenshot for your ready reference:
![image](https://github.com/frappe/lms/assets/111403440/5b17a1fd-fb25-40cb-86cf-9609a451dc8c)

**Comment by pateljannat** [comment]
@mkashif1973 can you please share the steps to replicate this scenario.

**Comment by mkashif1973** [comment]
Once user submit the quiz answers, we try to check it by visiting switch to desk and then select quiz submission to check the user submitted results.

**Comment by pateljannat** [comment]
@mkashif1973 can you please share a site where I can check this?

**Comment by niraj2477** [comment]
@mkashif1973  @pateljannat   Issue has been fixed here https://github.com/frappe/lms/pull/586
