### ISSUE TITLE
Course Completion % is not showing correctly

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#568]
each lesson didn't have quiz, course completion % is not showing correctly
example
I have
2 chapter
chapter 1 had 1 lesson
chapter 2 had 2 lessons

I had only 1 quiz on chatper 2, lesson 2
even I had completed all lessons and quizzes, system shown only 33%
then I had added another quiz to chapter 1 and lesson 1 , then student took the quiz system changed to 66%
![image](https://github.com/frappe/lms/assets/62122640/82db4aa9-cf62-452e-b00d-c50a69163d53)

![Uploading image.png…]()

Frappe Framework: v15.0.0-dev (HEAD)

Frappe LMS: v1.0.0 (HEAD)

**Comment by pateljannat** [comment]
So right now, when a user scrolls a lesson it's marked as complete. I know this is not a full-proof logic and we will be making changes to it.

**Comment by thida-bcn** [comment]
thank you
