### ISSUE TITLE
While creating new Class or Live Class showing date 20-07-2020

### ISSUE THREAD

**Issue by Govind-Jangid** [frappe/lms#575]
**Describe the bug**
While creating new Class or Live Class showing date 20-07-2020 even after change.

**To Reproduce**
1. Go to 'Class'
2. Click on 'Create Class'
3. Scroll down to 'Dialog Box'
4. Default Date is 20-07-2020

**Expected behavior**
Date Should be changable 

**Screenshots**

https://github.com/frappe/lms/assets/63184660/11ec8c60-17a6-4c32-8a3d-b9ee1afd3fff

**Desktop:**
 - OS: [MacOS Ventura]
 - Browser [chrome, safari]
 - Version [Version 13.4.1 (c) ]

**Smartphone:**
 - Device: [iPhone14]
 - OS: [iOS 16]
 - Browser [safari]
 - Version [16.4]

**Comment by pateljannat** [comment]
@Govind-Jangid if you are on Frappe v14, please switch to the develop branch.
