### ISSUE TITLE
Customised certificate generation

### ISSUE THREAD

**Issue by ramdasr04** [frappe/lms#585]
Was wondering whether the certificate that's automatically generated when a user finishes a quiz can be customised. We'd like to add an additional logo as well as more information on the certificate such as the signature of the course instructor

**Comment by pateljannat** [comment]
@ramdasr04 The certificate template comes from a Print Format. You can create a Print Format of your own for LMS Certificate doctype and mark it as default. The system will then pick the default print format to generate the certificate.

**Comment by ramdasr04** [comment]
> @ramdasr04 The certificate template comes from a Print Format. You can create a Print Format of your own for LMS Certificate doctype and mark it as default. The system will then pick the default print format to generate the certificate.


 Should the new certificate template be made by tweaking the html and css code?

**Comment by ramdasr04** [comment]
@pateljannat is it possible to upload our own certificate (our own design) as a pdf or so? If not, please assist to how additional logos can be

**Comment by pateljannat** [comment]
@ramdasr04 you can only do this by creating a print format of your own. If you don't know HTML, you can duplicate the current print format and edit values in the same.
