### ISSUE TITLE
Adding Social media buttons to Footer

### ISSUE THREAD

**Issue by akashss-cdf** [frappe/lms#590]
How to add social media buttons to footer of the frappe site

**Comment by niraj2477** [comment]
You can use `Footer Items` from  `Website Setting`

<img width="1354" alt="Screenshot 2023-08-14 at 3 22 59 PM" src="https://github.com/frappe/lms/assets/28840468/60aa5af1-ef8b-4208-855f-0144ab74979a">

**Comment by pateljannat** [comment]
@akashss-cdf did this work for you?
