### ISSUE TITLE
Getting Error from LMS app while updating the Employee via Data Import

### ISSUE THREAD

**Issue by mubi64** [frappe/lms#593]
**Describe the bug**
I recently installed LMS app, when I am updating employee via Data Import (which has already his pic attached in Employee and User Doctype), an exception is being thrown from the LMS app, please find the below screenshoots:

**Screenshots**

<img width="1412" alt="image" src="https://github.com/frappe/lms/assets/17858365/8d62bc96-820f-435f-9495-9647b084f364">

<img width="1412" alt="image" src="https://github.com/frappe/lms/assets/17858365/43cd3b4a-0f6f-4567-85f7-4e25f2d4ebe6">

as it can be seen that exception is being thrown from LMS utils.py line 583 from `validate_image` method

ERPNext: v14.10.0 (version-14)
Frappe Framework: v14.39.0 (version-14)
Frappe HR: v14.10.0 (version-14)
Frappe LMS: v1.0.0 (main)

**Comment by pateljannat** [comment]
@mubi64 please take the latest pull of the app and deploy again on your site.

**Comment by mubi64** [comment]
@pateljannat thanks for instant fix, appreciated!
