### ISSUE TITLE
Uploader is not working in LMS

### ISSUE THREAD

**Issue by mubi64** [frappe/lms#597]
**Describe the bug**
While creating a course when I am clicking on Upload Image, it is not showing the uploader in popup, just a blank popup with 2 buttons, here is the SS

**Screenshots**

<img width="1428" alt="image" src="https://github.com/frappe/lms/assets/17858365/d113019e-3715-448c-a9d8-aa067dd954ad">

Same is the case when adding some upload while creating lessons:

<img width="1428" alt="image" src="https://github.com/frappe/lms/assets/17858365/cfb9eb22-ca96-421d-bc7d-e9b716364280">

ERPNext: v14.10.0 (version-14)
Frappe Framework: v14.39.0 (version-14)
Frappe HR: v14.10.0 (version-14)
Frappe LMS: v1.0.0 (main)

**Comment by pateljannat** [comment]
@mubi64 You will need to be on the develop branch to use LMS

**Comment by mubi64** [comment]
> @mubi64 You need to be on the develop branch to use LMS

@pateljannat I am using version-14 branch, is there any way to make this working at version-14? because there are many sites on my bench and switching it to the develop branch can create a mess.

**Comment by N4K185** [comment]
I am also encountering a similar error. Can someone help? I am using it in a production environment.
![2023-08-25_163740](https://github.com/frappe/lms/assets/142808475/1781f2aa-d3df-408f-997a-6d17e1d0059d)

**Comment by pateljannat** [comment]
@mubi64 now that v15 has been released you should upgrade your sites to it.

@N4K185 please switch to v15
