### ISSUE TITLE
 Custom Passing Percentage for Quizzes

### ISSUE THREAD

**Issue by sumit-158** [frappe/lms#604]
The proposed feature aims to enhance the flexibility of the system's assessment tools by allowing instructors and administrators to customize the passing percentage for quizzes. Currently, the passing percentage is fixed at 100%, which can be quite restrictive in various educational contexts. By implementing this feature, we can empower educators to tailor assessments to their specific course requirements while maintaining a high level of control and flexibility.

**Comment by pateljannat** [comment]
Fixed with https://github.com/frappe/lms/pull/646
