### ISSUE TITLE
Whatsapp integration

### ISSUE THREAD

**Issue by ramdasr04** [frappe/lms#609]
Is it possible to integrate WhatsApp into frappe? If so, how would I do that?

**Comment by pateljannat** [comment]
There are 3 integrations available on Frappe Cloud Marketplace. You can check them out.

https://frappecloud.com/marketplace/apps/whatsapp_integration
https://frappecloud.com/marketplace/apps/whatsapp_app
https://frappecloud.com/marketplace/apps/whatsapp_plus
