### ISSUE TITLE
Paid Course Checkout is not working

### ISSUE THREAD

**Issue by idmlabhishek** [frappe/lms#611]
**Describe the bug**

When a user tries to buy a course she lands on the billing page which looks like http://two.localhost:8000/billing/<coursename>
The page is rendered with "Proceed to Payment" button not responding at all. On checking the console log in the browser this is the error we get 
"Uncaught TypeError: frappe.ui.form.make_control is not a function"

**To Reproduce**
1. Go to 'http://<siteurl>/billing/<coursename>'
2. Click on 'Proceed To Payment'
3. Open the Developer Console in Chrome

**Expected behavior**
A UI which captures the details of the user and a worknig proceed to Payment button, which allows user to make the payment

**Screenshots**
<img width="1767" alt="image" src="https://github.com/frappe/lms/assets/143377554/3acc2cee-84d7-4980-816a-540be5402476">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by pateljannat** [comment]
This will be fixed with #600

**Comment by idmlabhishek** [comment]
Hi @pateljannat 
While this issues has disappeared I am now facing another issue which throws a 500 server error while the page tries to download controls.bundle.js
I think there is some basic includes missing which forms the frappe.boot object in the web page. 
Can you please take a look and help me find this. 
I don't mind raising a PR if you could point me towards a solution here 

Thanks Abhishek

**Comment by idmlabhishek** [comment]
This is sorted... The issue was that I was on version 14 codeline of frappe
