### ISSUE TITLE
Error in Page_rendered.py

### ISSUE THREAD

**Issue by idmlabhishek** [frappe/lms#615]
**Describe the bug**
I am getting an Uncaught Server Exception when I try to access /people page on lms portal. On further investigation I figured out that I have a User created without a username in my system and hence the error. 

**To Reproduce**
1. Create a user in the system without a Username
2. Go to /people page
3. You'd see an error

**Expected behavior**
Page should still render

**Additional context**
The easiest fix would be to change Line 27 of page_renderers.py to 

```
if (username != None):
		return get_profile_url_prefix() + username

```

This will ensure that the page renders and for this user's profile we are redirected to /None page.

**Comment by pateljannat** [comment]
@idmlabhishek this issue has been fixed through FC right?
