### ISSUE TITLE
Thumbnail issue when sharing our platforms link.

### ISSUE THREAD

**Issue by ramdasr04** [frappe/lms#618]
When sending our LMS links through LinkedIn messages, the thumbnail that shows is the picture of one of our course instructors instead of our logo. Can this be fixed? And secondarily, there is no thumbnail at all when sending through Facebook, Instagram, and WhatsApp messages. Is there a fix for this? 

This is what appears when sharing our link through LinkedIn: 

<img width="447" alt="Screenshot 2023-09-19 at 16 05 37" src="https://github.com/frappe/lms/assets/141899699/bbbdd104-f88b-4cb5-93e0-0845c50340f2">

**Comment by pateljannat** [comment]
@ramdasr04 Your home page comes from the Web Page DocType.

There you can set Meta information like Title and Image. These meta details are used to show previews on such platforms.

<img width="1301" alt="Screenshot 2023-09-21 at 5 51 49 PM" src="https://github.com/frappe/lms/assets/31363128/47e76b28-3945-4097-a7d3-f9e2f6025e05">'

Set an image here and clear the website cache from the website settings. Then try sharing the link again.

**Comment by pateljannat** [comment]
@ramdasr04 is this working for you?
