### ISSUE TITLE
discussion will not update after add new reply

### ISSUE THREAD

**Issue by tomnattle** [frappe/lms#621]
on  discussion page, when student submit a reply to discussion,data has commit to server, but page does not update,unliss i reload page’，when current user is administrator,its work, i found that  recive messag is controlled by websocket.

![image](https://github.com/frappe/lms/assets/10323202/b2f8a2ae-5fba-4fa4-b246-3cf33ad4e96d)

![image](https://github.com/frappe/lms/assets/10323202/f1aae419-9fb0-4186-8d28-fbae1b06b9f4)
i found the reson is that , socket has been close when server has error.

![image](https://github.com/frappe/lms/assets/10323202/06bdfd21-ed0e-4f55-91b3-662ef0a99b3c)
this caurse websoket close,

**To Reproduce**

**Comment by pateljannat** [comment]
Works fine on new version
