### ISSUE TITLE
Upload a video from your local machine to the File Doctype

### ISSUE THREAD

**Issue by AhmadReda** [frappe/lms#631]
I have uploaded a video to File Doctype and made it public 
then I added this syntax {{ Video("/files/0-python-for-beginners-programming-tutorial.mp4") }} to the body field of the lesson doctype
and it doesn't appear on the website as a video it appears as a text

![image](https://github.com/frappe/lms/assets/26819123/5f533075-5d0d-42f4-910d-e2771f22ba99)

**Comment by pateljannat** [comment]
@AhmadReda Remove the space between Video and (. It should be {{ Video("url") }}

**Comment by finaldzn** [comment]
there is an issue with videos that are uploaded to an external S3, the https:// link doesn't work, the : is repalce by the unicode equivalent and thus the client thinks that the file is on the server, works perfectly fine when you are editing tho...

**Comment by pateljannat** [comment]
@finaldzn can you share the video recording replicating this issue
