### ISSUE TITLE
UX: Content validation on lesson

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/lms#636]
When I hit save without the content, it doesn't give feedback (that content is mandatory) and doesn't save.

<img width="983" alt="CleanShot 2023-10-04 at 15 41 21@2x" src="https://github.com/frappe/lms/assets/34810212/0b050fd8-de7c-49d2-999b-34c03e1cfe4d">

**Comment by pateljannat** [comment]
@NagariaHussain this is working fine for me on Chrome and arc. Can you try again at your end?


https://github.com/frappe/lms/assets/31363128/8899a741-3c41-4635-8773-c2ca589dbb0b
