### ISSUE TITLE
Uncaught error on Add Course from the Batch portal Page

### ISSUE THREAD

**Issue by muchai** [frappe/lms#641]
Error when adding course from the Batch page

**To Reproduce**
Create a batch
Open LMS Portal
Open Batches
Click on add course

**Expected behavior**
Add course dialog

**Screenshots**
![image](https://github.com/frappe/lms/assets/1822868/f026f34f-26cd-42c2-be0b-a483cf1186cf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - 
ERPNext: v14.43.0 (HEAD)
Frappe Framework: v14.51.0 (HEAD)
Frappe LMS: v1.0.0 (HEAD)

**Comment by pateljannat** [comment]
@muchai LMS app is compatible with develop(v15) of Frappe

**Comment by muchai** [comment]
@pateljannat Interesting. We have it installed on v14, and all demos we do on v14. All our scenarios are demos to multiple leads so far though.
Will set it up on v15. Thank you.
