### ISSUE TITLE
Couldn't save LMS Quiz as Total Marks is Missing Fields with recent changes to LMS Quiz.

### ISSUE THREAD

**Issue by asharamseervi** [frappe/lms#664]
**Describe the bug**

I thought to give a try, LMS Quiz and LMS Questions Doctypes, as these were part of recent development. I set up a fresh site, and created LMS Quiz, as shown in the screenshot, added questions. But, Due to mandatory fields i.e. Total Marks, required in the LMS Quiz
Total Marks

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a Fresh site.
2. Go to LMS Quiz.
3. Add questions. And, add needed inputs to all fields like passing percentage or marks.
4. Save and See error.

**Expected behavior**
I guess Total Marks is now of no need. It should be part of LMS Quiz Submission while there is already Score, Out of Score, sort of. I am still not sure, what Total Marks is meant for. Kindly look into it.

**Screenshots**
<img width="1369" alt="Screenshot 2023-10-27 at 1 04 29 AM" src="https://github.com/frappe/lms/assets/5942572/5ae5e7ad-3b60-4c32-9509-29e5de71266c">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: v14

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pateljannat** [comment]
@asharamseervi as you mentioned, I created a new site and created a quiz on it. But I did not face any such issues.

<img width="1429" alt="Screenshot 2023-10-30 at 11 33 17 AM" src="https://github.com/frappe/lms/assets/31363128/7c90cc24-76fd-436f-bdde-e08d2ea3a1ff">


Total Marks gets set by the system before the document is saved. Its present in LMS Quiz doctype to give an idea to instructors about the total at the time of quiz creation.

**Comment by asharamseervi** [comment]
Hey @pateljannat, 

Thank you for updating the information. 

I have tested this with v14 and also tried with a fresh instance. However, I'm still facing an issue with the Total Marks field. The problem persists and I'm unable to save the Quiz. 

However, if I disable the mandatory option from the LMS Doctype, it works as intended. I believe there might be some glitch with the before_save function or something similar, but I'm not entirely sure.

**Comment by pateljannat** [comment]
@asharamseervi LMS isn't compatible with v14 as of now. Was your new instance on v15?

**Comment by asharamseervi** [comment]
No, as v15 has some design issues to be fixed. Therefore, we haven't migrated to v15, but I'll test there soon.

**Comment by asharamseervi** [comment]
Thanks @rtdany10
