### ISSUE TITLE
Upload video directly to lms but can not save in lession

### ISSUE THREAD

**Issue by lamphanjk** [frappe/lms#678]
When I upload in the body of content, it worked properly , but when I save , the system throw the issue: Please set the document name

1. Go to "Add lession"
2. Click on 'plus icon" in content table, and click on " Upload". 
3. After upload , the image/video appear on the content . And click on "Save"
4. The error appear.

**Screenshots**
![image](https://github.com/frappe/lms/assets/48834692/2487a55f-9681-424a-980a-c76e61a99639)

**Comment by pateljannat** [comment]
@lamphanjk which version of Frappe are you on?

**Comment by lamphanjk** [comment]
before I used Frappe v15-dev. 
And Already updated all but still the same error. 

![image](https://github.com/frappe/lms/assets/48834692/6dd43010-2209-4442-ba55-e4d4634f2206)

**Comment by pateljannat** [comment]
Please switch to the latest version of the app.
