### ISSUE TITLE
Chapter and lesson restriction within a course, when moving from one chapter /lesson to the next.

### ISSUE THREAD

**Issue by Nahiempie** [frappe/lms#735]
**Is your feature request related to a problem? Please describe.**
I want to build a Frappe course where I am able to set a restriction so my students are not able to go from one chapter to another, without having made sure they completed the lessons and quizzes from one. I want to be able to check if they completed the quiz, and then can move on to the next chapter. It's very frustrating from a learning experience perspective that I can not do that now. They have to go through all the modules in a specific order. But now, they can just go to the end and say complete. I can of course see it in the data if they actually completed all the quizzes, but I want to provide clarity on this before hand by having better UI in place. Like a restriction.

**Describe the solution you'd like**
What a perfect solution would look like to me is to be able to say for each lesson I built, "restricted - need to complete before next chapter is unlocked", or something like that. 

**Describe alternatives you've considered**
I have not seen or considered alternatives that provide the same value and experience for students. 

**Additional context**
Additional important context. At the end of my course, student get a completion code they have to provide. Now they can go there from the beginning of the course. This is also why I would like to have a restriction per chapter and per lesson in place, so they are not able to get it. They first have to go through the entire Course and when they are finished with all chapters and lessons, then they can get the completion code. 

**How do I solve this? Help?!**

**Comment by joaomarcosjova** [comment]
To achieve the level of restriction and control you're looking for in your Frappe course, you might need to customize the platform or find a learning management system (LMS) that offers such features. Here are some potential solutions and steps you could take:

1. **Customize Frappe**: If Frappe allows for customization, you could potentially work with a developer to add the functionality you need. This might involve creating a custom plugin or module that enforces the restrictions you want, such as requiring completion of quizzes before progressing to the next chapter.

2. **Look for Frappe Extensions or Plugins**: Explore if there are existing extensions or plugins for Frappe that offer the functionality you need. Sometimes, community-developed extensions can provide the features you're looking for, or they can serve as a starting point for customization.

3. **Integrate with a Learning Management System (LMS)**: Consider integrating your Frappe course with an LMS that supports the level of restriction and control you want. There are many LMS options available, both open-source and commercial, that offer advanced features for managing course progression, quiz completion requirements, and student tracking.

4. **Explore Frappe Community or Forums**: Engage with the Frappe community or forums to see if others have faced similar challenges or have developed solutions that could meet your needs. Sometimes, community members or developers might have already created tools or extensions that address your requirements.

5. **Develop a Custom Solution**: If existing options don't meet your needs, you might need to develop a custom solution tailored specifically to your requirements. This could involve building a separate system that integrates with Frappe to handle course progression, quiz completion tracking, and issuing completion codes.

Regardless of the approach you choose, it's important to carefully plan and test your solution to ensure it provides the desired level of control and functionality while maintaining a positive learning experience for your students.

**Comment by pateljannat** [comment]
@Nahiempie we don't believe in having such restrictions in the system. Learning cannot be enforced. Even if such restrictions are put in place, it's very easy to rig them. I can just start the video and leave and do something else till the video is completed. Such restrictions give no benefits. For quizzes, you can anyways check the percentage the student scored.
