### ISSUE TITLE
Currently, this app depends on the develop branch of frappe.

### ISSUE THREAD

**Issue by ahmadRagheb** [frappe/lms#737]
hi
can we have a supported branch like v15 or v14, 
it's hard to use this app with a frappe development active branch in a production env. 
At lease the latest stable one v15

**Comment by pateljannat** [comment]
@ahmadRagheb you can use the main branch with frappe version-15

**Comment by ahmadRagheb** [comment]
thank you @pateljannat  , now i can move to 15 with no worries
