### ISSUE TITLE
✨ Badges ✨

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/lms#748]
More specific of https://github.com/frappe/lms/issues/392

Ability to configure badges for course or training. Maybe a "LMS Badge" doctype with below fields:

* image (the actual illustration that will be displayed on student profile)
* applied on (course or batch)
* some kind of allocation rule (on completion, x% of completion etc.)

For allocation, a separate doctype named "LMS Badge Allocation" or something that links a given badge with a student (user).

**Comment by pateljannat** [comment]
#795
