### ISSUE TITLE
Rewrite Issues

### ISSUE THREAD

**Issue by pateljannat** [frappe/lms#757]
If you face any issues in the develop branch, add then to this list.

- [x] Quiz progress

**Comment by NagariaHussain** [comment]
![image](https://github.com/frappe/lms/assets/34810212/9ae9f5e8-cd61-4028-8135-c96732baae01)

**Comment by NagariaHussain** [comment]
![CleanShot 2024-04-03 at 16 00 34@2x](https://github.com/frappe/lms/assets/34810212/5b3c73f5-4305-4fd1-8d98-b69fec9828c9)

Form Error Handling

**Comment by NagariaHussain** [comment]
Should take me to edit course view after course creation, currently stays as is

**Comment by pateljannat** [comment]
> Should take me to edit course view after course creation, currently stays as is

Fixed
