### ISSUE TITLE
Site Not Secure 

### ISSUE THREAD

**Issue by msalim79** [frappe/lms#765]
![Screenshot 2024-04-08 at 15 26 08](https://github.com/frappe/lms/assets/30749464/9729fade-2ab1-49f1-b087-4a908d390e08)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: macbook air
 - Browser chrome

**Additional context**

**Comment by pateljannat** [comment]
@msalim79 unable to replicate

<img width="1440" alt="Screenshot 2024-04-17 at 10 59 00 AM" src="https://github.com/frappe/lms/assets/31363128/7c05a9ef-800e-42e0-a23d-9d9dae2330b7">

**Comment by pateljannat** [comment]
Closing the issue. Reopen is needed.
