### ISSUE TITLE
Error On Resume Upload to Job Portal

### ISSUE THREAD

**Issue by nomi-gee** [frappe/lms#775]
When a user go to apply job upload resume then this error comes up

![image](https://github.com/frappe/lms/assets/41115216/c12e1f91-50e4-419f-a6c2-caf965fccc02)

**Comment by nomi-gee** [comment]
@pateljannat

**Comment by pateljannat** [comment]
@nomi-gee can you please check if there is any error in the console and share that as well.

**Comment by nomi-gee** [comment]
> @nomi-gee can you please check if there is any error in the console and share that as well.

`{
    "exception": "AttributeError: 'str' object has no attribute 'get'",
    "exc_type": "AttributeError",
    "_exc_source": "lms (app)",
    "exc": "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 110, in application\\n    response = frappe.api.handle(request)\\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 49, in handle\\n    data = endpoint(**arguments)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 36, in handle_rpc_call\\n    return frappe.handler.handle()\\n           ^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 49, in handle\\n    data = execute_cmd(cmd)\\n           ^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 85, in execute_cmd\\n    return frappe.call(method, **frappe.form_dict)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 1803, in call\\n    return fn(*args, **newargs)\\n           ^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/utils/typing_validations.py\\\", line 31, in wrapper\\n    return func(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/client.py\\\", line 201, in insert\\n    return insert_doc(doc).as_dict()\\n           ^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/client.py\\\", line 484, in insert_doc\\n    return frappe.get_doc(doc).insert()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 311, in insert\\n    self.run_method(\\\"after_insert\\\")\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 968, in run_method\\n    out = Document.hook(fn)(self, *args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1332, in composer\\n    return composed(self, method, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1310, in runner\\n    add_to_return_value(self, fn(self, *args, **kwargs))\\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 965, in fn\\n    return method_object(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/lms/lms/job/doctype/lms_job_application/lms_job_application.py\\\", line 18, in after_insert\\n    self.send_email_to_employer()\\n  File \\\"apps/lms/lms/job/doctype/lms_job_application/lms_job_application.py\\\", line 34, in send_email_to_employer\\n    frappe.sendmail(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 872, in sendmail\\n    return builder.process(send_now=now)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/email/doctype/email_queue/email_queue.py\\\", line 721, in process\\n    queue_data = self.as_dict(include_recipients=False)\\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/email/doctype/email_queue/email_queue.py\\\", line 766, in as_dict\\n    mail = self.prepare_email_content()\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/email/doctype/email_queue/email_queue.py\\\", line 688, in prepare_email_content\\n    mail = get_email(\\n           ^^^^^^^^^^\\n  File \\\"apps/frappe/frappe/email/email_body.py\\\", line 95, in get_email\\n    if attach.get(\\\"fcontent\\\") is None:\\n       ^^^^^^^^^^\\nAttributeError: 'str' object has no attribute 'get'\\n\"]"
}`

**Comment by pateljannat** [comment]
Fixed with #778
