### ISSUE TITLE
Enable to Schedule an Evaluation

### ISSUE THREAD

**Issue by TinasheErasmus** [frappe/lms#780]
Error when attempting to schedule an evaluation.

1. When you go to Frappe Framework Bootcamp, Dubai batch
2. Click on Schedule Evaluation button
3. Select course, as Frappe Framework Course, date and slot
4. when you click submit, an error pops up with the message " Internal Server Error"

![image](https://github.com/frappe/lms/assets/72265393/7b28c742-aa6d-4005-bb8a-aa6c2c25595d)

**Comment by pateljannat** [comment]
@TinasheErasmus some changes were made to this batch yesterday. I checked the Frappe School system and saw that you were able to schedule the evaluation later. Let me know if there is still some issue
