### ISSUE TITLE
how to login as an admin in local setup ?

### ISSUE THREAD

**Issue by Pradeep119** [frappe/lms#784]
Hi Team,

I have setup lms locally. how can i log as an admin ? what is the default username and password ?

Thanks

**Comment by Pradeep119** [comment]
found
username : Administrator
password: admin

**Comment by taowang1993** [comment]
Any idea how to change the default admin password?

<img width="806" alt="image" src="https://github.com/user-attachments/assets/40a0879d-1b91-4fbd-814f-f6418ea03ae9">
