### ISSUE TITLE
Error While running Migration: A field with the name title already exists in Employee Onboarding Template

### ISSUE THREAD

**Issue by maniamartial** [frappe/lms#786]
Getting an error which prevents migration of LMS app.
![Screenshot from 2024-04-26 10-36-33](https://github.com/frappe/lms/assets/60258622/d9be9756-bb10-44b8-b384-8d54baa9f951)
#### Issue Description:
The current implementation of duplicate field name validation in the Employee Onboarding Template fails to prevent the creation of duplicate fields, leading to potential data integrity issues. To address this issue, it is proposed to remove the conflicting field entries directly from the custom_field.json file associated with the template.

#### Proposed Solution:
Remove the entry corresponding to the duplicate field name from the custom_field.json file of the Employee Onboarding Template. This action should effectively resolve the duplicate field name conflict and ensure that users cannot inadvertently create conflicting fields.
![image](https://github.com/frappe/lms/assets/60258622/8a977f60-1c8d-4d37-97dc-d920153a80cc)

**Comment by pateljannat** [comment]
@maniamartial This doctype belongs to the HRMS app. It's not a part of LMS.
