### ISSUE TITLE
Trying to import User data throws error in the email validation part

### ISSUE THREAD

**Issue by Bowrna** [frappe/lms#789]
I have cloned the repo and started the LMS via Docker and wanted to try importing User Data as CSV.
While Importing the data it throws error as InvalidEmailAddress error from frappe. Attaching the screenshot 

1. Go to Users
2. Click on Import Data
3.Create Data CSV from blank template and upload it

Expected behavior
Data getting imported and User getting created

<img width="785" alt="Screenshot 2024-04-29 at 11 11 41 AM" src="https://github.com/frappe/lms/assets/10162465/0dec4efe-df3a-4d9e-961b-e6e7cf4957c5">
<img width="1367" alt="Screenshot 2024-04-29 at 11 11 19 AM" src="https://github.com/frappe/lms/assets/10162465/22f90e12-6c54-4e5b-a2e6-5006a2034020">

Desktop 
 - OS: iOS
 - Browser Chrome
 - Version Version 123.0.6312.87 (Official Build) (arm64)

**Comment by pateljannat** [comment]
@Bowrna seems like for one of the rows the email ID is incorrect. Please verify the csv once before importing. If you feel the issue persists, share the csv with me.

**Comment by Bowrna** [comment]
@pateljannat I exported the sample CSV from the LMS and added the emails alone. I didn't add the column names on my own. Let me check again and let you know.
