### ISSUE TITLE
Notifications on topic reply

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/lms#797]
The topic creator as well as the course instructor should be notified on new replies etc. 

For example, I added a reply to the topic, the student should get a notification email for the same:

![CleanShot 2024-05-03 at 12 32 54@2x](https://github.com/frappe/lms/assets/34810212/c4f31c04-9e45-43c3-ad73-68781c370d38)

**Comment by pateljannat** [comment]
Closed with #836
