### ISSUE TITLE
Permissions Based on Course Chapter and Lessons

### ISSUE THREAD

**Issue by Ashutosh-Dubey-realgroup** [frappe/lms#798]
The Permission level is not possible now in Course chapter and lessons. 

We have a scenario where we have several Divisions and Departments.

We have created a course Purchase Process and in that we have several chapters ad lessons.
Like , Indent , PO, GRN, Issue etc. 

We want to give permission to view course to specific Division and Department persons

Like Indent and PO can be viewed by Purchase department users 
GRN and Issue can be viewed By Store Department and so on.

It will be so useful if we can give permissions based on Chapters and lessons as well.

Please Consider my request 

Thanks

**Comment by pateljannat** [comment]
@Ashutosh-Dubey-realgroup you can create courses based on departments. And then only enroll people who belong to that department in that course. Let me know if you have further queries.

**Comment by Ashutosh-Dubey-realgroup** [comment]
@pateljannat  thanks for your response 
I have done the work you told made courses based on departments. 
But i have one more query 
I have created different user groups which acts as departments in which users belong to that department will be added 
But when i go to course enrolment there is option to enrol members but how can i enrol user groups at once 

I have more than 1000 users and like 100 courses based on department and user role 

If i need to enrol one by one it will take so much time 

Is there any way to enrol the user group to a course.

**Comment by pateljannat** [comment]
For now, you can enroll users using the Data Import tool. https://docs.erpnext.com/docs/user/manual/en/data-import
