### ISSUE TITLE
Quiz Summary didn't show correctly

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#806]
![image](https://github.com/frappe/lms/assets/62122640/73cebab6-8793-486e-822e-318d8426119b)

**Comment by pateljannat** [comment]
@thida-bcn I was unable to replicate this. Can you please recall the steps you followed that led to this?

<img width="836" alt="Screenshot 2024-05-10 at 5 26 06 PM" src="https://github.com/frappe/lms/assets/31363128/60c7e2f7-39b9-48ff-981a-5e39ecf6d9ac">

**Comment by thida-bcn** [comment]
during the quiz or end of quiz without submit, reload page and start from beginning quiz 
system will show more than 100%
First Time
![image](https://github.com/frappe/lms/assets/62122640/894f20c4-2a5b-4e0d-8246-fac6a22328c0)
Second Time
![image](https://github.com/frappe/lms/assets/62122640/25791d89-2565-4ea8-9932-08676b8bcf4c)
After Submit 2nd Time
![image](https://github.com/frappe/lms/assets/62122640/b8a13c0d-a6d5-4e15-8efd-b6467d041313)

**Comment by pateljannat** [comment]
@thida-bcn I followed the steps you mentioned but was still unable to replicate the issue


https://github.com/frappe/lms/assets/31363128/ce93adc8-1dcf-41f3-97ff-08a4af7db960
