### ISSUE TITLE
Can we remove some menu?

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#813]
![image](https://github.com/frappe/lms/assets/62122640/1bd94397-83aa-42fc-a6e6-ccc566a88f68)
hello,
I don't want to show
Certified Participants
Jobs
Statistics
for Students, how can we configure?

**Comment by dlaufen** [comment]
I did this as well.  But you wouldn't want this change in LMS, those are baseline feature. If you don't want them I think you need to do it manually or from your own module or setup.

Manually, you can edit the "Website Settings" Navbar Tab to delete the entries you don't want. You would have to do this after each install.  The other way would be to do it as part of your own module and deletel the items you don't want with some python code post install.  There are hooks for that.

With a module, you can add an _after_install_ entry in hooks.py and then add some code to do the removals:
```
def after_install():
    add_pages_to_nav()  # I add my own stuff
    adjust_pages_to_nav() #remove what I didn't want


def adjust_pages_to_nav():
    """Removes LMS Nav Bar items we are not using."""
    frappe.clear_cache()
    remove_list =["Batches", "Courses", "Jobs"]
    parent = frappe.get_doc ("Website Settings")
    
    for nav_pg in list(parent.top_bar_items):
        if nav_pg.label in remove_list:
            l = nav_pg.label
            parent.remove(nav_pg)            
            frappe.delete_doc("Top Bar Item", nav_pg.name)
            
    for index, row in enumerate(parent.top_bar_items):
        row.idx = index + 1 # +1 to keep page number from 1 .. N        
    parent.save()
```
This removes them for everyone, not just students.

Doing something similar but by role requires you to use the website context hook so you can change the page based on some role.   Look at how _update_website_context_ can be used.

This should help you automate what you need.  Check out the install.py and hooks.py in LMS.  That will help too.

Good Luck

**Comment by thida-bcn** [comment]
thanks
let me try
Thanks and Regards,
Thida
Business Development Director

Business Centric Network Company Limited
+959 977 160 671
+959 254 677 192
***@***.***
https://businesscentricnetwork.com/

**Comment by thida-bcn** [comment]
@pateljannat 
hello, is this possible to remove some menu?
because for LMS using at school, we don't need job

**Comment by pateljannat** [comment]
#849

**Comment by thida-bcn** [comment]
I had put a few feedback
thanks
Thanks and Regards,
Thida
Business Development Director

Business Centric Network Company Limited
+959 977 160 671
+959 254 677 192
***@***.***
https://businesscentricnetwork.com/

**Comment by dlaufen** [comment]
Thanks for this.  With new Vue based code, there is no longer the cut point on the server I described above.  It seems Vue doesn't have a good way to override a component so putting the controls app is helpful.  Lots of uses where Jobs and other pages may not be needed.  Thanks again!
