### ISSUE TITLE
Not redirecting to login page when clicking start learning

### ISSUE THREAD

**Issue by Ashutosh-Dubey-realgroup** [frappe/lms#823]
**Describe the bug**

I have frappe LMS as the default homepage in my website 
I have some courses and lessons in it 
when user click start learning from any course it redirect to login page but when we click the start learning from the course lesson page it come back to course preview page.

**To Reproduce**
Set the LMS as the default homepage
tap on any course 
tap on any lesson 
it will show start learning 
Press start learning button 
It will redirect back to course page

**Expected behavior**
When Click the start learning button it should redirect to login page not back to course page.

**Screenshots**
Here is a screen recording with the bug

https://github.com/frappe/lms/assets/141140479/3ebd09c0-0db0-402d-bcf1-113f3c51d869

**Desktop (please complete the following information):**
 - OS: [Ubuntu 24]
 - Browser [Firefox]
 - Version [125.0 (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Poco X6 Pro, Iphone 14Pro, Oneplus 9Pro]
 - OS: [Android 14 , Android 13, Ios17.4 ]
 - Browser [Chrome , Safari , Brave]
 - Version [124, 17.4, 1.64]

**Additional context**

**Comment by pateljannat** [comment]
@Ashutosh-Dubey-realgroup From the screenshot it seems that you are not logged in so when you click on **Start Learning** from the course page it shows a toast asking you to Please Login and then redirects you to the Login page.

**Comment by Ashutosh-Dubey-realgroup** [comment]
@pateljannat  thanks for the response I was saying that when we open any course chapter and click login to it is is not redirecting to login it is redirecting back to course preview page
