### ISSUE TITLE
Reschedule the evaluation

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#829]
is this possible to reschedule the evaluation
![image](https://github.com/frappe/lms/assets/62122640/654405a6-cd2e-4c87-8dee-4e0547e25c28)
![image](https://github.com/frappe/lms/assets/62122640/8a3f5b68-b2aa-4efc-9087-9cde5449205e)

**Comment by pateljannat** [comment]
@thida-bcn evals can't be rescheduled if you already have an upcoming evaluation
