### ISSUE TITLE
User Name

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#835]
![image](https://github.com/frappe/lms/assets/62122640/e28cc5ef-a573-444a-a18a-a590514f70de)
Under Batch, when we adding students, is this possible to allow user to show Student's Name
Now, it shown only email

**Comment by pateljannat** [comment]
@thida-bcn This is linked to the User doctype. In the User doctype email ID is the unique identification for every user. Hence the dropdown shows emails and not name.
