### ISSUE TITLE
Can't check own certificate at frappe school

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#839]
![image](https://github.com/frappe/lms/assets/62122640/afa2ddb3-9632-43c1-b825-13a11c2cd1cf)
we can't even check for own certificate
![image](https://github.com/frappe/lms/assets/62122640/6df9ee39-f7de-43f5-b6ec-fcf35b4f6aa4)

**Comment by pateljannat** [comment]
Fixed with #841
