### ISSUE TITLE
Unable to add quiz as lesson

### ISSUE THREAD

**Issue by stealthbolt** [frappe/lms#843]
**Describe the bug**
I am unable to add quizzes or Google Slides as per the documentation in the content editor. When I hover over the editor, I don't see any components to add. Additionally, I am unable to add a quiz using the "{{Quiz()}}" syntax, as I am encountering a "resource not found" error. If anyone has successfully managed this, please provide the steps. Your help would be appreciated.

**To Reproduce**
1. Go to lessons
2. Click on create new lesson
3. Scroll down to content editor

**Expected behavior**
The quiz should be added after creation and components must be shown

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 125.0.6422.77 (Official Build) (64-bit)

**Comment by pateljannat** [comment]
@stealthbolt which version of the app are you on?

**Comment by stealthbolt** [comment]
version 1.0.0

**Comment by pateljannat** [comment]
@stealthbolt when you click on the editor you see a plus icon. Clicking on it opens up a menu that lets you add all such components. If this is not the case for you, then can you record a video highlight how the editor is for you currently.

**Comment by yoc-san** [comment]
have the same bug and version. I am working with the version on Frappe Cloud.


https://github.com/user-attachments/assets/5cdcf3bd-5f11-4d70-8e0b-b41606f5bc75

**Comment by yoc-san** [comment]
@pateljannat

**Comment by pateljannat** [comment]
@yoc-san the syntax used is wrong. Also with the new version, you don't need to use it. Use the portal to add a quiz to the lesson.
