### ISSUE TITLE
iframe Embed Support for lesson content

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/lms#855]
My use case is to embed codesandbox:

![CleanShot 2024-06-05 at 09 20 21@2x](https://github.com/frappe/lms/assets/34810212/cdc28442-6868-42dd-ad34-0e218361f865)

**Comment by NagariaHussain** [comment]
Example embed code:

```html
<iframe src="https://codesandbox.io/embed/2q4qvv?view=editor+%2B+preview&module=%2Findex.html"
     style="width:100%; height: 500px; border:0; border-radius: 4px; overflow:hidden;"
     title="dom-1"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```

**Comment by pateljannat** [comment]
@NagariaHussain Codepen embed works. You can try that.

**Comment by MuhammadKazimSadiq** [comment]
can iframe embeds be used generally? for example embed of spotify or instagram.

**Comment by pateljannat** [comment]
Allowing any iframe can be a risk to security as people may end up adding embeds from any random source. Right now embeds from YouTube, Vimeo, Codepen, Google Slides are allowed. I can add support for more trusted sources.

**Comment by PatrickDEissler** [comment]
@pateljannat 
One of our clients would embed documents (especially non-public videos) from Google Drive.

Could you please implement this? We would be really happy about that.
We already had a quick look for implementing ourselves, but thought we are not yet too familiar with the codebase.

**Comment by pateljannat** [comment]
#898

**Comment by scooter7** [comment]
Hi @pateljannat , if you could add support for streamlit app embeds, that would be much appreciated. Thanks!

**Comment by BonifacioCalindoro** [comment]
Being able to embed loom videos would also be a quick win

**Comment by baramuttaqien-alt** [comment]
@pateljannat can u add canva embed? needed that for now
