### ISSUE TITLE
JS Audio Player/ Video Player Library

### ISSUE THREAD

**Issue by MuhammadKazimSadiq** [frappe/lms#858]
The videos/ audios in the lesson should show up in a better audio/ video player.

**Comment by pateljannat** [comment]
@MuhammadKazimSadiq can you please elaborate on this.

**Comment by MuhammadKazimSadiq** [comment]
Currently when uploading audios/ videos to the lesson content, they show up in the native browser players (at least the audios, haven't checked videos), which doesn't look the greatest. Ideally using a js player would really enhance how the whole thing looks and feels.

**Comment by pateljannat** [comment]
#882
