### ISSUE TITLE
Links for audios and videos

### ISSUE THREAD

**Issue by MuhammadKazimSadiq** [frappe/lms#859]
The lesson content should allow users to just use link of audios/ videos instead of actually uploading the audio/ video. 
Many users use external storage options to store their media content.

**Comment by pateljannat** [comment]
@MuhammadKazimSadiq what kind of external source? YouTube and Vimeo are already supported for videos.

**Comment by MuhammadKazimSadiq** [comment]
I couldn't figure out how to work with Vimeo. Didn't work for me for some reason. I'll re-visit that
Besides that, is it not possible to just use a link for a video, regardless of where it is hosted?

**Comment by pateljannat** [comment]
@MuhammadKazimSadiq That can't be done as people may try to add any random source, which can cause security issues. Hence only YouTube and Vimeo are allowed as they are popular and trusted sources
