### ISSUE TITLE
Stable and Versioned Branches

### ISSUE THREAD

**Issue by PatrickDEissler** [frappe/lms#879]
# Desired Solution
## 1) Stable Branch
Which branch can be used for stable, productive sites on V14?

## 2) Versioned Branches
It would be great to consistently have versioned branches:
- develop
- version-15
- version-14
- ...

# Context
Our customer really likes the LMS and might also invest in some features/ development (not sure yet, where it goes). 
However, the current develop branch does not seem reliable enough. 

Also it seems that the site's availability was affected since we use LMS (not proved yet).

**Comment by pateljannat** [comment]
@PatrickDEissler the main branch is the stable branch. The develop branch gets all new features merged regularly. Right now releases to the main branch are not regular. I'll announce the release a few weeks before merging it to main.

**Comment by PatrickDEissler** [comment]
@pateljannat 
Alright, thanks. Where/how do you announce it? 
I would like to make sure that I don't miss out on it.
