### ISSUE TITLE
Issue with uploading files to lesson content

### ISSUE THREAD

**Issue by Zack00e** [frappe/lms#880]
Nothing happens when uploading PDF file or doc file into my lesson content, but it works for mp4 and photos.

![image](https://github.com/frappe/lms/assets/40050189/894f3ae9-f6ee-42ce-9868-fec598085111)

**Comment by Zack00e** [comment]
any update?

**Comment by pateljannat** [comment]
@Zack00e I'll fix this

**Comment by Zack00e** [comment]
thaks let me know when it fixed
