### ISSUE TITLE
PDF file upload error

### ISSUE THREAD

**Issue by stealthbolt** [frappe/lms#887]
**Describe the bug**
Pdf file not uploading

**To Reproduce**
1. Go to 'lms portal'
2. Click on 'edit'
3. Scroll down to 'upload file section and upload any pdf'

**Expected behavior**
pdf must be added to the chapter I created.

**Screenshots**
![Screenshot 2024-06-24 112733](https://github.com/frappe/lms/assets/161610865/c6aba0c4-647b-40b4-88ec-85d782bf64cb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft edge
 - Version: 126.0.2592.68 (Official build) (64-bit)

**Additional context**

**Comment by pateljannat** [comment]
@stealthbolt attach a video or screenshot replicating the same

**Comment by stealthbolt** [comment]
![Screenshot 2024-06-24 145520](https://github.com/frappe/lms/assets/161610865/987e4308-c835-45a8-a9cb-fc1a20001b04)

**Comment by pateljannat** [comment]
Fixed with #884
