### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by nilpatel42** [frappe/lms#893]
**Describe the bug**
Icons not showing properly when lesson edit
In some screen its showing over text, in some screen its showing in left side of text, it depends on size of the screen

**To Reproduce**
1. Go to 'Lesson' (Dashboard)
2. Edit Lesson

**Screenshots**

https://github.com/frappe/lms/assets/135511086/8a4951d9-bc25-4e56-ac1e-1240c4586222

Frappe LMS: v1.0.0 (develop)

**Comment by pateljannat** [comment]
@nilpatel42 what is the screen size here?

**Comment by nilpatel42** [comment]
Laptop : 1366 x 768
Monitor : 1920 x 1080

Issue In Both Screen Size
