### ISSUE TITLE
User vs Total Sign Up

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#914]
![image](https://github.com/frappe/lms/assets/62122640/6828a152-8dd1-4aba-8f07-46477a0d0014)
![image](https://github.com/frappe/lms/assets/62122640/c1b7d825-6939-4140-8e00-0b197263e89f)

active user is only 261
but sign up show 263
there was 2 additional users, i supposed 'administrator' and 'guest'
please check

**Comment by thida-bcn** [comment]
@pateljannat hello, please check total sing up

**Comment by thida-bcn** [comment]
@pateljannat please check 
Total User is only 21
![image](https://github.com/user-attachments/assets/63ff01f7-20fd-4eb9-a3f6-a0785aa6772f)
status shown 23
![image](https://github.com/user-attachments/assets/674f8729-6897-4565-8e30-1ab7b0f9266d)

extra 2 users
administrator and guest

**Comment by pateljannat** [comment]
Fixed with #964
