### ISSUE TITLE
When we hide courses from side bar, want to change default page

### ISSUE THREAD

**Issue by thida-bcn** [frappe/lms#923]
LMS Side Bar Settings >> uncheck Course
![image](https://github.com/frappe/lms/assets/62122640/6c074d16-1d36-4343-a945-79edef522fff)
When we go to Visit LMS Portal, system still go to Courses, if system allow user to change page which user want to set default will be better
![image](https://github.com/frappe/lms/assets/62122640/56832359-a27a-4f22-9e86-ce37a5d0d7ae)

**Comment by pateljannat** [comment]
You can do so from Portal Settings
