### ISSUE TITLE
Prevent loading LMS unless user is logged in

### ISSUE THREAD

**Issue by KevinFaro** [frappe/lms#934]
**Is your feature request related to a problem? Please describe.**
We're looking in to using Frappe LMS for internal staff training. We're already using ERPNext internally so our users have Frappe accounts. We want to make it so the LMS cannot be loaded at all unless the user is logged in to Frappe. Logged out users are currently able to browse courses and other details.

**Describe the solution you'd like**
A checkbox (or role select) on the LMS settings page that allows us to limit access to logged in users or specific roles.

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by pateljannat** [comment]
Hello @KevinFaro ,

I can't add this setting. But you can customize this. Add some javascript in the Website Theme, that checks the route of the page, if it is /lms and the user is not logged in, redirect them to the login page.

Let me know if you need more clarity on this.
