### ISSUE TITLE
impossible to sedn email  lms  v2.0.3

### ISSUE THREAD

**Issue by maksimvelbaum** [frappe/lms#958]
Hi , 
Maybe stupid question but
After fresh install LMS in  docker   v 2.0.3 on self hosted server and setup email domain and account ,still impossible to send email ,  email server don't have any logs , means  LMS even  didn't make any reuest.  Maybe somebody can explain me whan I'm doing wrong , same smtp server working perfectly with other software 

`frappe-1 | 11:46:02 web.1 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/typing_validations.py:32: DeprecationWarning: Options {'cmd': 'frappe.core.doctype.communication.email.make'} used in frappe.core.doctype.communication.email.make are deprecated or unsupported  
frappe-1 | 11:46:02 web.1 | return func(*args, **kwargs)  
frappe-1 | 11:46:03 web.1 | ERROR PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): ('HASH', '#0000001a', 1, 3215)  
frappe-1 | 11:46:03 web.1 | ERROR PropertyValue: Unknown syntax or no value: 0 3px 6px #0000001a  
frappe-1 | 11:46:03 web.1 | ERROR CSSStyleDeclaration: Syntax Error in Property: box-shadow:0 3px 6px #0000001a  
frappe-1 | 11:46:03 web.1 | 172.18.0.1 - - [07/Aug/2024 11:46:03] "POST /api/method/frappe.core.doctype.communication.email.make HTTP/1.1" 200 -  
frappe-1 | 11:46:03 web.1 | 172.18.0.1 - - [07/Aug/2024 11:46:03] "GET /api/method/frappe.desk.form.load.getdoc?doctype=Email%20Account&name=Notifications&_=1723030766592 HTTP/1.1" 200 -`

smtp server tested  with difrent setups 

SMTP host: mail.boomreports.app.
Port: 465
Use Explicit TLS encryption: Yes
Use Implicit TLS/SSL encryption: SSL
Use Authentication: Yes
Authentication username: [test@boomreports.app](mailto:test@boomreports.app)
Authentication password: [hidden]
Email from: [test@boomreports.app](mailto:test@boomreports.app)
Email to: [test@boomreports.app](mailto:test@boomreports.app)
Your IP: 80.235.104.234

This service is provided by https://dnschecker.org/

SMTP host: mail.boomreports.app.
Port: 587
Use Explicit TLS encryption: Yes
Use Implicit TLS/SSL encryption: TLS
Use Authentication: Yes
Authentication username: [test@boomreports.app](mailto:test@boomreports.app)
Authentication password: [hidden]
Email from: [test@boomreports.app](mailto:test@boomreports.app)
Email to: [test@boomreports.app](mailto:test@boomreports.app)
Your IP: 80.235.104.234

This service is provided by https://dnschecker.org/

**Comment by pateljannat** [comment]
@maksimvelbaum from where are you trying to send these emails

**Comment by maksimvelbaum** [comment]
Hi,  @pateljannat 
Thank you for your reply. I tried sending emails from different places. First of all, I added the email domain, IMAP, and SMTP server. Then, I added an email account and set it as the default outgoing email account. On the main page of the email account, there is a ‘Send email’ button, which I used for testing. I also created new users, and according to the logs, it seems like the LMS tried to send some messages, but none of them arrived. I started to think that the server might be blocking some ports, so I wrote a simple Python script to check the SMTP, and everything worked with the script. Now I just don't know where mistake can be. Aplication installed in Docker container and all container are up and running.

**Comment by maksimvelbaum** [comment]
Forgot to add I also tried  install aplication without this line  in [init.sh](https://github.com/frappe/lms/blob/develop/docker/init.sh)

bench --site lms.localhost set-config mute_emails 1   but it also not helped

**Comment by pateljannat** [comment]
@maksimvelbaum check your site config to verify if this is still present

**Comment by maksimvelbaum** [comment]
@pateljannat  Hi ,   

 if  understand correct that is site config , it is exists in docker container  frappe/bench:latest ,    
 lms.localhost     site_config.json

  {
 "db_name": "_43470b366e9bc286",
 "db_password": "Tq39hPxHQMZ0mPZ0",
 "db_type": "mariadb",
 "db_user": "_43470b366e9bc286",
 "developer_mode": 1,
 "encryption_key": "4TcWYloi2e_XEDHV79OcgCdKV25Qa2J1AdO8rAw2qAY="
}


or you mean somethig else ?

**Comment by maksimvelbaum** [comment]
do I need to add there some of this settings  ?

https://frappeframework.com/docs/user/en/basics/site_config


![image](https://github.com/user-attachments/assets/3c53ff18-45e1-4ec4-8278-cb40830210c8)

**Comment by maksimvelbaum** [comment]
@pateljannat 

This config  working for me , but all settings in email module looks like not saved or not working , no idea why.   Anyway  THANK YOU!   you are relly helped me , even this configuration will work for me fine , we need it only for internal use. 
{
 "db_name": "_906b3ed65f3cee74",
 "db_password": "hYnE3ilS1AzNM5wi",
 "db_type": "mariadb",
 "db_user": "_906b3ed65f3cee74",
 "developer_mode": 1,
 "email_sender_name": "test@boomreports.app",
 "encryption_key": "HTVkf7Vz8UhwB0L5azl9kJBLCNGOSeaon7sQAfKEWtY=",
 "auto_email_id": "test@boomreports.app",
 "mail_login": "test@boomreports.app",
 "mail_password": "",
 "mail_port": 465,
 "mail_server": "mail.boomreports.app",
 "use_ssl": true,
 "use_tls": false
}
