### ISSUE TITLE
Feature request: Image and Video Embedding

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/lms#973]
- [ ] Embed images in between the contents of the lessons.
- [ ] Embed videos for courses and lessons.

**Comment by pateljannat** [comment]
@mohsinalimat all these feature already work in the current system. 

<img width="1440" alt="Screenshot 2024-08-20 at 6 20 01 PM" src="https://github.com/user-attachments/assets/462f324e-686f-45a1-a0f5-979a99ab2f91">
<img width="1440" alt="Screenshot 2024-08-20 at 6 21 06 PM" src="https://github.com/user-attachments/assets/edcb67bc-f929-49d7-9384-fb51ba5ca356">
