### ISSUE TITLE
A Member List in Popup to create new Enrollment is incorrect

### ISSUE THREAD

**Issue by hyperdatavn** [frappe/lms#982]
**Describe the bug**
A Member List in Popup to create new Enrollment is incorrect

**To Reproduce**
1. Use mobile layout
2. Click on Enrollment
3. Click Create New Encrollment
4. Click Members 
5. See List User, it display not enough

**Expected behavior**
A List User will display enough the same in Edit Full Form 

**Screenshots**
![image](https://github.com/user-attachments/assets/799f4d79-fea6-41d3-8fd9-5e3611589b06)
![image](https://github.com/user-attachments/assets/0bfb3230-36c8-4ac3-a506-dd81b2c1fcf8)

**Comment by pateljannat** [comment]
By default, the framework shows only System Users on quick entry. On the full form, you will see all users. This behavior is the same on desktop as well as mobile.

@hyperdatavn
