### ISSUE TITLE
Unable to create a Course in LMS

### ISSUE THREAD

**Issue by Arundhati-maitra** [frappe/lms#999]
Hello,

We are currently in the process of creating a course within our LMS. However, we have encountered two significant issues that we need assistance with:

**Lack of Markdown Syntax for Embedding Content:** Our Lesson doctype in the LMS does not include the specialized markdown syntax required for embedding videos, quizzes, assessments, etc. Could you please advise on how we can incorporate this syntax into our lessons?

**Content Visibility Issue in LMS Portal:** While accessing the course through the LMS portal, we are only able to see the headlines, but the actual content within the lessons is not being displayed. We would greatly appreciate your help in resolving this issue.

I am attaching a few screenshots for your reference, which should provide more clarity on the challenges we are facing.

Thanks and Regards,

![erp lesson](https://github.com/user-attachments/assets/392ce035-673a-41e6-b78f-dedbbf8ade6d)
![image](https://github.com/user-attachments/assets/774066de-b5c4-4b57-8de7-2b1c864147cc)

**Comment by NagariaHussain** [comment]
The latest version doesn't have any of these issues, closing.

**Comment by Arundhati-maitra** [comment]
Our issue is also solved.

Thanks, and Regards,

Arundhati Maitra.





Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
